import { CATALOG, DEFAULT_STATE, FIELD_SPECS, REALISM_MODULES, MODULE_LEVELS } from './data/catalog.js';
import { PRESETS } from './data/presets.js';
import { compileDetailed, compileConcise, compileJson, compileNegative } from './core/compiler.js';
import { validationStatus } from './core/validation.js';
import { normalizeState } from './core/state.js';
const $=id=>document.getElementById(id);const STORAGE_KEY='physics-prompt-studio-general-v5';let activeView='detailed';let referenceAttached=false;
const sectionFields={reference:['idea','referenceRole'],scene:['captureType','time','location','customLocation','people','ratio'],subject:['age','pose','customPose','expression','hair','customHair','beard','customBeard','glasses','customGlasses','clothing','customClothing'],camera:['framing','focalLength','distance','yaw','pitch','roll'],lighting:['lightSource','customLightSource','lightDirection','lightFalloff','exposure','hdr','whiteBalance'],notes:['notes']};
function fillSelect(id,options){const select=$(id);if(!select)return;select.replaceChildren(...options.map(option=>{const el=document.createElement('option');el.value=option.id;el.textContent=option.label;return el;}));}
function populate(){for(const [field,options] of Object.entries(CATALOG))fillSelect(field,options);fillSelect('preset',PRESETS.map(p=>({id:p.id,label:p.label})));const modules=$('realismModules');modules.replaceChildren(...REALISM_MODULES.map(module=>{const wrap=document.createElement('label');wrap.className='module-card';const title=document.createElement('span');title.textContent=module.label;const select=document.createElement('select');select.dataset.module=module.id;for(const level of MODULE_LEVELS){const opt=document.createElement('option');opt.value=level.id;opt.textContent=level.label;select.append(opt);}wrap.append(title,select);return wrap;}));}
function readState(){const value=id=>$(id)?.value??'';const modules={};document.querySelectorAll('[data-module]').forEach(el=>modules[el.dataset.module]=el.value);return normalizeState({idea:value('idea'),referenceRole:value('referenceRole'),referenceAttached,captureType:value('captureType'),time:value('time'),location:value('location'),customLocation:value('customLocation'),people:value('people'),ratio:value('ratio'),age:value('age'),pose:value('pose'),customPose:value('customPose'),expression:value('expression'),hair:value('hair'),customHair:value('customHair'),beard:value('beard'),customBeard:value('customBeard'),glasses:value('glasses'),customGlasses:value('customGlasses'),clothing:value('clothing'),customClothing:value('customClothing'),framing:value('framing'),focalLength:value('focalLength'),distance:value('distance'),yaw:value('yaw'),pitch:value('pitch'),roll:value('roll'),lightSource:value('lightSource'),customLightSource:value('customLightSource'),lightDirection:value('lightDirection'),lightFalloff:value('lightFalloff'),exposure:value('exposure'),hdr:value('hdr'),whiteBalance:value('whiteBalance'),modules,notes:value('notes')});}
function setState(input){const state=normalizeState(input);for(const [id,val] of Object.entries(state))if(id!=='modules'&&id!=='referenceAttached'&&$(id))$(id).value=val;document.querySelectorAll('[data-module]').forEach(el=>el.value=state.modules[el.dataset.module]);referenceAttached=Boolean(state.referenceAttached);toggleCustom();render();}
function outputFor(state){if(activeView==='concise')return compileConcise(state);if(activeView==='json')return compileJson(state);if(activeView==='negative')return compileNegative(state);return compileDetailed(state);}
function render(){const state=readState();const status=validationStatus(state);$('output').textContent=outputFor(state);$('liveState').textContent=status.blocked?'BLOCKED':status.issues.length?'CHECK':'VALID';$('liveState').dataset.state=status.blocked?'blocked':status.issues.length?'check':'valid';$('warningCount').textContent=String(status.issues.length);$('checklist').replaceChildren(...(status.issues.length?status.issues:[{severity:'ok',code:'OK',message:'لا توجد تعارضات مكتشفة.'}]).map(issue=>{const li=document.createElement('li');li.className=`issue-${issue.severity}`;li.textContent=`${issue.code}: ${issue.message}`;return li;}));localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
function toggleCustom(){for(const [select,wrap] of [['location','customLocationWrap'],['pose','customPoseWrap'],['hair','customHairWrap'],['beard','customBeardWrap'],['glasses','customGlassesWrap'],['clothing','customClothingWrap'],['lightSource','customLightSourceWrap']])if($(wrap))$(wrap).hidden=$(select)?.value!=='custom';}
function filterSelect(selectId,searchId){const source=CATALOG[selectId];const query=$(searchId).value.trim().toLowerCase();const current=$(selectId).value;const filtered=!query?source:source.filter(item=>item.label.toLowerCase().includes(query)||(item.prompt||'').toLowerCase().includes(query)||item.id==='custom');fillSelect(selectId,filtered);if(filtered.some(x=>x.id===current))$(selectId).value=current;render();}
function bind(){$('promptForm').addEventListener('input',()=>{toggleCustom();render();});$('promptForm').addEventListener('change',()=>{toggleCustom();render();});$('locationSearch').addEventListener('input',()=>filterSelect('location','locationSearch'));$('clothingSearch').addEventListener('input',()=>filterSelect('clothing','clothingSearch'));$('referenceImage').addEventListener('change',event=>{referenceAttached=Boolean(event.target.files?.length);$('fileStatus').textContent=referenceAttached?`تم اختيار: ${event.target.files[0].name}`:'تبقى الصورة على جهازك؛ نسجل فقط وجودها ودورها.';render();});$('applyPreset').addEventListener('click',()=>{const preset=PRESETS.find(p=>p.id===$('preset').value);if(preset)setState({...DEFAULT_STATE,...preset.values,modules:DEFAULT_STATE.modules});});$('resetAll').addEventListener('click',()=>{referenceAttached=false;$('referenceImage').value='';setState(DEFAULT_STATE);});document.querySelectorAll('.section-reset').forEach(button=>button.addEventListener('click',()=>{const section=button.dataset.reset;if(section==='realism'){document.querySelectorAll('[data-module]').forEach(el=>el.value=DEFAULT_STATE.modules[el.dataset.module]);render();return;}for(const field of sectionFields[section]||[])if($(field))$(field).value=DEFAULT_STATE[field];toggleCustom();render();}));document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>{activeView=button.dataset.view;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b===button));render();}));$('copy').addEventListener('click',async()=>{await navigator.clipboard.writeText($('output').textContent);$('copy').textContent='تم النسخ';setTimeout(()=>$('copy').textContent='نسخ',900);});}
populate();for(const [field,spec] of Object.entries(FIELD_SPECS))if($(field)){$(field).min=spec.min;$(field).max=spec.max;}bind();try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');setState(saved||DEFAULT_STATE);}catch{setState(DEFAULT_STATE);}
