import { CAR_CATALOG, CAR_DEFAULT_STATE, analyzeCarSelfieIntent, isCarOptionCompatible } from './data/carSelfieCatalog.js';
import { normalizeCarState, carValidationStatus } from './core/carSelfieValidation.js';
import { compileCarSelfieDetailed, compileCarSelfieConcise, compileCarSelfieJson, compileCarSelfieNegative } from './core/carSelfieCompiler.js';
const $=id=>document.getElementById(id),STORAGE_KEY='physics-prompt-studio-car-selfie-v1';let activeView='detailed',referenceAttached=false;
function fill(field,state,preserve=true){const select=$(field);if(!select)return;const current=select.value,options=CAR_CATALOG[field]||[];select.replaceChildren(...options.map(item=>{const o=document.createElement('option');o.value=item.id;o.textContent=item.label;const ok=isCarOptionCompatible(field,item.id,state);o.disabled=!ok;o.hidden=!ok;return o;}));if(preserve&&options.some(x=>x.id===current&&isCarOptionCompatible(field,x.id,state)))select.value=current;if(!isCarOptionCompatible(field,select.value,state)){const first=options.find(x=>isCarOptionCompatible(field,x.id,state));if(first)select.value=first.id;}}
function populate(state){for(const field of Object.keys(CAR_CATALOG))fill(field,state,false);}const value=id=>$(id)?.value??'';
function readState(){return normalizeCarState({initialRequest:value('initialRequest'),referenceAttached,referenceRole:value('referenceRole'),vehicleProfile:value('vehicleProfile'),vehicleState:value('vehicleState'),seat:value('seat'),captureMode:value('captureMode'),time:value('time'),locationContext:value('locationContext'),physicsMode:value('physicsMode'),apparentAge:value('apparentAge'),expression:value('expression'),clothing:value('clothing'),handPose:value('handPose'),framing:value('framing'),focalLength:value('focalLength'),distance:value('distance'),yaw:value('yaw'),pitch:value('pitch'),roll:value('roll'),cabinMaterial:value('cabinMaterial'),clusterType:value('clusterType'),roofType:value('roofType'),lightSource:value('lightSource'),exposure:value('exposure'),hdr:value('hdr'),whiteBalance:value('whiteBalance'),notes:value('notes')});}
function refilter(state){for(const field of ['captureMode','handPose','lightSource','locationContext'])fill(field,state,true);return readState();}
function setState(input){const state=normalizeCarState(input);populate(state);for(const [key,val] of Object.entries(state))if($(key)&&key!=='referenceAttached')$(key).value=val;referenceAttached=state.referenceAttached;refilter(state);render();}
function out(state){if(activeView==='concise')return compileCarSelfieConcise(state);if(activeView==='json')return compileCarSelfieJson(state);if(activeView==='negative')return compileCarSelfieNegative();return compileCarSelfieDetailed(state);}
function render(){let state=readState();state=refilter(state);const status=carValidationStatus(state);$('output').textContent=out(state);$('issueCount').textContent=String(status.issues.length);$('liveState').textContent=status.blocked?'BLOCKED':status.issues.length?'CHECK':'VALID';$('liveState').dataset.state=status.blocked?'blocked':status.issues.length?'check':'valid';const list=status.issues.length?status.issues:[{severity:'ok',code:'OK',message:'التركيبة متناسقة مع قواعد المقصورة الحالية.'}];$('issues').replaceChildren(...list.map(i=>{const li=document.createElement('li');li.className=i.severity;li.textContent=`${i.code}: ${i.message}`;return li;}));localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
function applyIntent(){const analysis=analyzeCarSelfieIntent(value('initialRequest')),request=value('initialRequest');setState({...analysis.recommended,initialRequest:request,referenceAttached,referenceRole:value('referenceRole')||'identity-only',notes:value('notes')});$('intentSummary').textContent=analysis.tags.length?`تم: ${analysis.tags.join(' · ')}`:'لم يجد كلمات حاسمة؛ طُبقت الحالة الافتراضية الحتمية.';}
$('carForm').addEventListener('change',render);$('carForm').addEventListener('input',render);$('analyzeIntent').addEventListener('click',applyIntent);$('referenceImage').addEventListener('change',e=>{referenceAttached=Boolean(e.target.files?.length);$('fileStatus').textContent=referenceAttached?`تم اختيار: ${e.target.files[0].name}`:'لم تُرفق صورة';render();});document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>{activeView=button.dataset.view;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b===button));render();}));$('copy').addEventListener('click',async()=>{await navigator.clipboard.writeText($('output').textContent);$('copy').textContent='تم النسخ';setTimeout(()=>$('copy').textContent='نسخ',900);});try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');setState(saved||CAR_DEFAULT_STATE);}catch{setState(CAR_DEFAULT_STATE);}
