import test from 'node:test';
import assert from 'node:assert/strict';
import { generateImagePrompt, CAMERA_PROFILES, FRAMING_OPTIONS } from '../core/prompt-generator.js';
import { SELFIE_POSES, POSE_HAND_USAGE, CLOTHING_CATALOG, CLOTHING_STYLING, HAND_INTERACTIONS, LOCATION_CATALOG, SELFIE_ANGLES, LIGHTING_PROFILES, getRemainingHands } from '../core/scene-builder.js';
import { compatibilitySnapshot } from '../core/scene-compatibility.js';
import { buildRealismPacket } from '../core/realistic-image-generator.js';

function sceneSection(prompt){ return prompt.split('[SCENE]\n')[1].split('\n\n[SAUDI CULTURAL DRESS]')[0]; }
function furnitureKinds(prompt){
  const scene=sceneSection(prompt);
  const patterns={chair:/The chair is a single discrete one-seat piece/i,counter:/The counter is a continuous solid structure/i,generic:/All furniture maintains a coherent 3D structure/i,desk:/The desk has a flat working surface/i,table:/The table has a continuous top/i};
  return Object.entries(patterns).filter(([,pattern])=>pattern.test(scene)).map(([kind])=>kind);
}
const compatibilityCatalogs={location:LOCATION_CATALOG,clothing:CLOTHING_CATALOG,pose:SELFIE_POSES,angle:SELFIE_ANGLES,lighting:LIGHTING_PROFILES,camera:CAMERA_PROFILES,framing:FRAMING_OPTIONS};

test("PR 14 desk guard direct_elevator_selfie stays generic",()=>{ const r=generateImagePrompt({"sceneType":"direct_elevator_selfie","locationValue":"residential_elevator","location":"inside an ordinary residential elevator in Saudi Arabia with metal or laminate wall panels, overhead practical light, control panel, slightly worn floor edges, and realistic confined-space reflections","poseValue":""}); assert.deepEqual(furnitureKinds(r.prompt),['generic']); assert.doesNotMatch(sceneSection(r.prompt),/The desk has|The table has|The chair is|The counter is/i); assert.equal(r.sections.length,23); assert.equal(r.validation.valid,true,r.validation.errors.join(' | ')); });
test("PR 14 desk guard close_face_selfie stays generic",()=>{ const r=generateImagePrompt({"sceneType":"close_face_selfie","locationValue":"residential_elevator","location":"inside an ordinary residential elevator in Saudi Arabia with metal or laminate wall panels, overhead practical light, control panel, slightly worn floor edges, and realistic confined-space reflections","poseValue":""}); assert.deepEqual(furnitureKinds(r.prompt),['generic']); assert.doesNotMatch(sceneSection(r.prompt),/The desk has|The table has|The chair is|The counter is/i); assert.equal(r.sections.length,23); assert.equal(r.validation.valid,true,r.validation.errors.join(' | ')); });
test("PR 14 desk guard open_shade_outdoor_selfie stays generic",()=>{ const r=generateImagePrompt({"sceneType":"open_shade_outdoor_selfie","locationValue":"palm_farm","location":"inside a Saudi palm farm with realistic rows, irrigation traces, soil, natural shade breakup, and ordinary agricultural details","poseValue":""}); assert.deepEqual(furnitureKinds(r.prompt),['generic']); assert.doesNotMatch(sceneSection(r.prompt),/The desk has|The table has|The chair is|The counter is/i); assert.equal(r.sections.length,23); assert.equal(r.validation.valid,true,r.validation.errors.join(' | ')); });
test("PR 14 hand usage standing_arms_crossed",()=>{ assert.equal(POSE_HAND_USAGE['standing_arms_crossed'],1); assert.equal(getRemainingHands('front_selfie','subject-held front-camera smartphone selfie','none','standing_arms_crossed'),0); });
test("PR 14 hand usage standing_hands_in_pockets",()=>{ assert.equal(POSE_HAND_USAGE['standing_hands_in_pockets'],1); assert.equal(getRemainingHands('front_selfie','subject-held front-camera smartphone selfie','none','standing_hands_in_pockets'),0); });
test("PR 14 hand usage seated_legs_crossed",()=>{ assert.equal(POSE_HAND_USAGE['seated_legs_crossed'],0); assert.equal(getRemainingHands('front_selfie','subject-held front-camera smartphone selfie','none','seated_legs_crossed'),1); });
test("PR 14 hand usage seated_elbow_on_table",()=>{ assert.equal(POSE_HAND_USAGE['seated_elbow_on_table'],1); assert.equal(getRemainingHands('front_selfie','subject-held front-camera smartphone selfie','none','seated_elbow_on_table'),0); });
test("PR 14 hand usage lean_railing",()=>{ assert.equal(POSE_HAND_USAGE['lean_railing'],0); assert.equal(getRemainingHands('front_selfie','subject-held front-camera smartphone selfie','none','lean_railing'),1); });
test("PR 14 hand usage standing_looking_away",()=>{ assert.equal(POSE_HAND_USAGE['standing_looking_away'],0); assert.equal(getRemainingHands('front_selfie','subject-held front-camera smartphone selfie','none','standing_looking_away'),1); });
test("PR 14 hand usage seated_leaning_forward",()=>{ assert.equal(POSE_HAND_USAGE['seated_leaning_forward'],0); assert.equal(getRemainingHands('front_selfie','subject-held front-camera smartphone selfie','none','seated_leaning_forward'),1); });
test("PR 14 hand usage walking_looking_back",()=>{ assert.equal(POSE_HAND_USAGE['walking_looking_back'],0); assert.equal(getRemainingHands('front_selfie','subject-held front-camera smartphone selfie','none','walking_looking_back'),1); });
test("PR 14 hand usage standing_stretching",()=>{ assert.equal(POSE_HAND_USAGE['standing_stretching'],0); assert.equal(getRemainingHands('front_selfie','subject-held front-camera smartphone selfie','none','standing_stretching'),1); });
test("PR 14 hand usage seated_reading_posture",()=>{ assert.equal(POSE_HAND_USAGE['seated_reading_posture'],1); assert.equal(getRemainingHands('front_selfie','subject-held front-camera smartphone selfie','none','seated_reading_posture'),0); });
test("PR 14 hand usage standing_hand_on_hip",()=>{ assert.equal(POSE_HAND_USAGE['standing_hand_on_hip'],1); assert.equal(getRemainingHands('front_selfie','subject-held front-camera smartphone selfie','none','standing_hand_on_hip'),0); });
test("PR 14 hand usage leaning_against_wall",()=>{ assert.equal(POSE_HAND_USAGE['leaning_against_wall'],0); assert.equal(getRemainingHands('front_selfie','subject-held front-camera smartphone selfie','none','leaning_against_wall'),1); });
test("PR 14 catalog and UI compatibility standing_arms_crossed",()=>{ const item=SELFIE_POSES.find((pose)=>pose.value==='standing_arms_crossed'); assert.ok(item); assert.ok(item.prompt.length>40); const snapshot=compatibilitySnapshot('standing_selfie',compatibilityCatalogs); assert.equal(snapshot.pose.some((pose)=>pose.value==='standing_arms_crossed'),true); });
test("PR 14 catalog and UI compatibility standing_hands_in_pockets",()=>{ const item=SELFIE_POSES.find((pose)=>pose.value==='standing_hands_in_pockets'); assert.ok(item); assert.ok(item.prompt.length>40); const snapshot=compatibilitySnapshot('standing_selfie',compatibilityCatalogs); assert.equal(snapshot.pose.some((pose)=>pose.value==='standing_hands_in_pockets'),true); });
test("PR 14 catalog and UI compatibility seated_legs_crossed",()=>{ const item=SELFIE_POSES.find((pose)=>pose.value==='seated_legs_crossed'); assert.ok(item); assert.ok(item.prompt.length>40); const snapshot=compatibilitySnapshot('seated_selfie',compatibilityCatalogs); assert.equal(snapshot.pose.some((pose)=>pose.value==='seated_legs_crossed'),true); });
test("PR 14 catalog and UI compatibility seated_elbow_on_table",()=>{ const item=SELFIE_POSES.find((pose)=>pose.value==='seated_elbow_on_table'); assert.ok(item); assert.ok(item.prompt.length>40); const snapshot=compatibilitySnapshot('seated_selfie',compatibilityCatalogs); assert.equal(snapshot.pose.some((pose)=>pose.value==='seated_elbow_on_table'),true); });
test("PR 14 catalog and UI compatibility lean_railing",()=>{ const item=SELFIE_POSES.find((pose)=>pose.value==='lean_railing'); assert.ok(item); assert.ok(item.prompt.length>40); const snapshot=compatibilitySnapshot('outdoor_selfie',compatibilityCatalogs); assert.equal(snapshot.pose.some((pose)=>pose.value==='lean_railing'),true); });
test("PR 14 catalog and UI compatibility standing_looking_away",()=>{ const item=SELFIE_POSES.find((pose)=>pose.value==='standing_looking_away'); assert.ok(item); assert.ok(item.prompt.length>40); const snapshot=compatibilitySnapshot('standing_selfie',compatibilityCatalogs); assert.equal(snapshot.pose.some((pose)=>pose.value==='standing_looking_away'),true); });
test("PR 14 catalog and UI compatibility seated_leaning_forward",()=>{ const item=SELFIE_POSES.find((pose)=>pose.value==='seated_leaning_forward'); assert.ok(item); assert.ok(item.prompt.length>40); const snapshot=compatibilitySnapshot('seated_selfie',compatibilityCatalogs); assert.equal(snapshot.pose.some((pose)=>pose.value==='seated_leaning_forward'),true); });
test("PR 14 catalog and UI compatibility walking_looking_back",()=>{ const item=SELFIE_POSES.find((pose)=>pose.value==='walking_looking_back'); assert.ok(item); assert.ok(item.prompt.length>40); const snapshot=compatibilitySnapshot('walking_selfie',compatibilityCatalogs); assert.equal(snapshot.pose.some((pose)=>pose.value==='walking_looking_back'),true); });
test("PR 14 catalog and UI compatibility standing_stretching",()=>{ const item=SELFIE_POSES.find((pose)=>pose.value==='standing_stretching'); assert.ok(item); assert.ok(item.prompt.length>40); const snapshot=compatibilitySnapshot('standing_selfie',compatibilityCatalogs); assert.equal(snapshot.pose.some((pose)=>pose.value==='standing_stretching'),true); });
test("PR 14 catalog and UI compatibility seated_reading_posture",()=>{ const item=SELFIE_POSES.find((pose)=>pose.value==='seated_reading_posture'); assert.ok(item); assert.ok(item.prompt.length>40); const snapshot=compatibilitySnapshot('seated_selfie',compatibilityCatalogs); assert.equal(snapshot.pose.some((pose)=>pose.value==='seated_reading_posture'),true); });
test("PR 14 catalog and UI compatibility standing_hand_on_hip",()=>{ const item=SELFIE_POSES.find((pose)=>pose.value==='standing_hand_on_hip'); assert.ok(item); assert.ok(item.prompt.length>40); const snapshot=compatibilitySnapshot('standing_selfie',compatibilityCatalogs); assert.equal(snapshot.pose.some((pose)=>pose.value==='standing_hand_on_hip'),true); });
test("PR 14 catalog and UI compatibility leaning_against_wall",()=>{ const item=SELFIE_POSES.find((pose)=>pose.value==='leaning_against_wall'); assert.ok(item); assert.ok(item.prompt.length>40); const snapshot=compatibilitySnapshot('outdoor_selfie',compatibilityCatalogs); assert.equal(snapshot.pose.some((pose)=>pose.value==='leaning_against_wall'),true); });
test("PR 14 furniture semantic standing_arms_crossed",()=>{ const r=generateImagePrompt({"sceneType":"direct_elevator_selfie","location":"inside an ordinary residential elevator in Saudi Arabia","poseValue":"standing_arms_crossed"}); assert.deepEqual(furnitureKinds(r.prompt),['generic']); assert.equal(r.sections.length,23); assert.equal(r.validation.valid,true,r.validation.errors.join(' | ')); });
test("PR 14 furniture semantic standing_hands_in_pockets",()=>{ const r=generateImagePrompt({"sceneType":"direct_elevator_selfie","location":"inside an ordinary residential elevator in Saudi Arabia","poseValue":"standing_hands_in_pockets"}); assert.deepEqual(furnitureKinds(r.prompt),['generic']); assert.equal(r.sections.length,23); assert.equal(r.validation.valid,true,r.validation.errors.join(' | ')); });
test("PR 14 furniture semantic seated_legs_crossed",()=>{ const r=generateImagePrompt({"sceneType":"cafe_selfie","location":"inside an ordinary Saudi cafe","poseValue":"seated_legs_crossed"}); assert.deepEqual(furnitureKinds(r.prompt),['chair']); assert.equal(r.sections.length,23); assert.equal(r.validation.valid,true,r.validation.errors.join(' | ')); });
test("PR 14 furniture semantic seated_elbow_on_table",()=>{ const r=generateImagePrompt({"sceneType":"cafe_selfie","location":"inside an ordinary Saudi cafe","poseValue":"seated_elbow_on_table"}); assert.deepEqual(furnitureKinds(r.prompt),['chair']); assert.equal(r.sections.length,23); assert.equal(r.validation.valid,true,r.validation.errors.join(' | ')); });
test("PR 14 furniture semantic lean_railing",()=>{ const r=generateImagePrompt({"sceneType":"cafe_selfie","location":"inside an ordinary Saudi cafe","poseValue":"lean_railing"}); assert.deepEqual(furnitureKinds(r.prompt),['counter']); assert.equal(r.sections.length,23); assert.equal(r.validation.valid,true,r.validation.errors.join(' | ')); });
test("PR 14 furniture semantic standing_looking_away",()=>{ const r=generateImagePrompt({"sceneType":"direct_elevator_selfie","location":"inside an ordinary residential elevator in Saudi Arabia","poseValue":"standing_looking_away"}); assert.deepEqual(furnitureKinds(r.prompt),['generic']); assert.equal(r.sections.length,23); assert.equal(r.validation.valid,true,r.validation.errors.join(' | ')); });
test("PR 14 furniture semantic seated_leaning_forward",()=>{ const r=generateImagePrompt({"sceneType":"cafe_selfie","location":"inside an ordinary Saudi cafe","poseValue":"seated_leaning_forward"}); assert.deepEqual(furnitureKinds(r.prompt),['chair']); assert.equal(r.sections.length,23); assert.equal(r.validation.valid,true,r.validation.errors.join(' | ')); });
test("PR 14 furniture semantic walking_looking_back",()=>{ const r=generateImagePrompt({"sceneType":"direct_elevator_selfie","location":"inside an ordinary residential elevator in Saudi Arabia","poseValue":"walking_looking_back"}); assert.deepEqual(furnitureKinds(r.prompt),['generic']); assert.equal(r.sections.length,23); assert.equal(r.validation.valid,true,r.validation.errors.join(' | ')); });
test("PR 14 furniture semantic standing_stretching",()=>{ const r=generateImagePrompt({"sceneType":"direct_elevator_selfie","location":"inside an ordinary residential elevator in Saudi Arabia","poseValue":"standing_stretching"}); assert.deepEqual(furnitureKinds(r.prompt),['generic']); assert.equal(r.sections.length,23); assert.equal(r.validation.valid,true,r.validation.errors.join(' | ')); });
test("PR 14 furniture semantic seated_reading_posture",()=>{ const r=generateImagePrompt({"sceneType":"cafe_selfie","location":"inside an ordinary Saudi cafe","poseValue":"seated_reading_posture"}); assert.deepEqual(furnitureKinds(r.prompt),['chair']); assert.equal(r.sections.length,23); assert.equal(r.validation.valid,true,r.validation.errors.join(' | ')); });
test("PR 14 furniture semantic standing_hand_on_hip",()=>{ const r=generateImagePrompt({"sceneType":"direct_elevator_selfie","location":"inside an ordinary residential elevator in Saudi Arabia","poseValue":"standing_hand_on_hip"}); assert.deepEqual(furnitureKinds(r.prompt),['generic']); assert.equal(r.sections.length,23); assert.equal(r.validation.valid,true,r.validation.errors.join(' | ')); });
test("PR 14 furniture semantic leaning_against_wall",()=>{ const r=generateImagePrompt({"sceneType":"direct_elevator_selfie","location":"inside an ordinary residential elevator in Saudi Arabia","poseValue":"leaning_against_wall"}); assert.deepEqual(furnitureKinds(r.prompt),['generic']); assert.equal(r.sections.length,23); assert.equal(r.validation.valid,true,r.validation.errors.join(' | ')); });
test("PR 14 action semantic standing_arms_crossed",()=>{ const packet=buildRealismPacket({sceneType:'front_selfie',requestedSceneType:'front_selfie',captureType:'subject-held front-camera smartphone selfie',poseValue:'standing_arms_crossed'}); assert.match(packet.action,/stand naturally/i); });
test("PR 14 action semantic standing_hands_in_pockets",()=>{ const packet=buildRealismPacket({sceneType:'front_selfie',requestedSceneType:'front_selfie',captureType:'subject-held front-camera smartphone selfie',poseValue:'standing_hands_in_pockets'}); assert.match(packet.action,/stand naturally/i); });
test("PR 14 action semantic seated_legs_crossed",()=>{ const packet=buildRealismPacket({sceneType:'front_selfie',requestedSceneType:'front_selfie',captureType:'subject-held front-camera smartphone selfie',poseValue:'seated_legs_crossed'}); assert.match(packet.action,/remain naturally seated/i); });
test("PR 14 action semantic seated_elbow_on_table",()=>{ const packet=buildRealismPacket({sceneType:'front_selfie',requestedSceneType:'front_selfie',captureType:'subject-held front-camera smartphone selfie',poseValue:'seated_elbow_on_table'}); assert.match(packet.action,/remain naturally seated/i); });
test("PR 14 action semantic lean_railing",()=>{ const packet=buildRealismPacket({sceneType:'front_selfie',requestedSceneType:'front_selfie',captureType:'subject-held front-camera smartphone selfie',poseValue:'lean_railing'}); assert.match(packet.action,/lean lightly/i); });
test("PR 14 action semantic standing_looking_away",()=>{ const packet=buildRealismPacket({sceneType:'front_selfie',requestedSceneType:'front_selfie',captureType:'subject-held front-camera smartphone selfie',poseValue:'standing_looking_away'}); assert.match(packet.action,/stand naturally/i); });
test("PR 14 action semantic seated_leaning_forward",()=>{ const packet=buildRealismPacket({sceneType:'front_selfie',requestedSceneType:'front_selfie',captureType:'subject-held front-camera smartphone selfie',poseValue:'seated_leaning_forward'}); assert.match(packet.action,/remain naturally seated/i); });
test("PR 14 action semantic walking_looking_back",()=>{ const packet=buildRealismPacket({sceneType:'front_selfie',requestedSceneType:'front_selfie',captureType:'subject-held front-camera smartphone selfie',poseValue:'walking_looking_back'}); assert.match(packet.action,/walk naturally/i); });
test("PR 14 action semantic standing_stretching",()=>{ const packet=buildRealismPacket({sceneType:'front_selfie',requestedSceneType:'front_selfie',captureType:'subject-held front-camera smartphone selfie',poseValue:'standing_stretching'}); assert.match(packet.action,/stand naturally/i); });
test("PR 14 action semantic seated_reading_posture",()=>{ const packet=buildRealismPacket({sceneType:'front_selfie',requestedSceneType:'front_selfie',captureType:'subject-held front-camera smartphone selfie',poseValue:'seated_reading_posture'}); assert.match(packet.action,/remain naturally seated/i); });
test("PR 14 action semantic standing_hand_on_hip",()=>{ const packet=buildRealismPacket({sceneType:'front_selfie',requestedSceneType:'front_selfie',captureType:'subject-held front-camera smartphone selfie',poseValue:'standing_hand_on_hip'}); assert.match(packet.action,/stand naturally/i); });
test("PR 14 action semantic leaning_against_wall",()=>{ const packet=buildRealismPacket({sceneType:'front_selfie',requestedSceneType:'front_selfie',captureType:'subject-held front-camera smartphone selfie',poseValue:'leaning_against_wall'}); assert.match(packet.action,/lean lightly/i); });
test('PR 14 clothing styling category counts',()=>{ assert.deepEqual(Object.fromEntries(Object.entries(CLOTHING_STYLING).map(([key,value])=>[key,value.length])),{thobe:6,shirt:10,tshirt:5,bisht:2,suit:3}); });
test('PR 14 every general clothing item has one of six categories',()=>{ const allowed=new Set(['thobe','shirt','tshirt','bisht','abaya','suit']); assert.equal(CLOTHING_CATALOG.length,209); for(const item of CLOTHING_CATALOG) assert.equal(allowed.has(item.category),true,item.value); });
test('PR 14 representative category mapping is stable',()=>{ const byValue=new Map(CLOTHING_CATALOG.map((item)=>[item.value,item.category])); assert.equal(byValue.get('white_thobe'),'thobe'); assert.equal(byValue.get('look-01'),'shirt'); assert.equal(byValue.get('white_tshirt'),'tshirt'); assert.equal(byValue.get('bisht_thobe'),'bisht'); assert.equal(byValue.get('black_abaya'),'abaya'); assert.equal(byValue.get('suit-navy-white'),'suit'); });
test('PR 14 thobe rolled sleeves reaches prompt and preserves 23 sections',()=>{ const r=generateImagePrompt({sceneType:'front_selfie',clothingValue:'white_thobe',clothingStyling:'sleeves-rolled'}); assert.match(r.prompt,/Roll the thobe sleeves/i); assert.equal(r.sections.length,23); assert.equal(r.validation.valid,true,r.validation.errors.join(' | ')); });
test('PR 14 shirt French tuck reaches prompt and preserves 23 sections',()=>{ const r=generateImagePrompt({sceneType:'front_selfie',clothingValue:'look-01',clothingStyling:'french-tuck'}); assert.match(r.prompt,/Tuck only the front section of the shirt/i); assert.equal(r.sections.length,23); assert.equal(r.validation.valid,true,r.validation.errors.join(' | ')); });
test('PR 14 cross-category styling does not leak',()=>{ const thobe=generateImagePrompt({sceneType:'front_selfie',clothingValue:'white_thobe',clothingStyling:'french-tuck'}); const shirt=generateImagePrompt({sceneType:'front_selfie',clothingValue:'look-01',clothingStyling:'suit-jacket-open'}); assert.doesNotMatch(thobe.prompt,/front section of the shirt/i); assert.doesNotMatch(shirt.prompt,/suit or jacket open at the front/i); });

test("PR 14 phase4 pose standing_hands_clasped_front registry coverage",()=>{ const value='standing_hands_clasped_front'; const item=SELFIE_POSES.find((pose)=>pose.value===value); assert.equal(item?.prompt,'standing with both hands loosely clasped in front of the waist at natural hip level, arms relaxed'); assert.equal(POSE_HAND_USAGE[value],0); assert.equal(compatibilitySnapshot('standing_selfie',compatibilityCatalogs).pose.some((pose)=>pose.value===value),true); assert.match(buildRealismPacket({sceneType:'front_selfie',requestedSceneType:'front_selfie',captureType:'subject-held front-camera smartphone selfie',poseValue:value}).action,/stand naturally/i); });
test("PR 14 phase4 pose standing_thumb_in_pocket registry coverage",()=>{ const value='standing_thumb_in_pocket'; const item=SELFIE_POSES.find((pose)=>pose.value===value); assert.equal(item?.prompt,'standing with the thumb of the free hand hooked into a front pocket while the other hand holds the phone'); assert.equal(POSE_HAND_USAGE[value],0); assert.equal(compatibilitySnapshot('standing_selfie',compatibilityCatalogs).pose.some((pose)=>pose.value===value),true); assert.match(buildRealismPacket({sceneType:'front_selfie',requestedSceneType:'front_selfie',captureType:'subject-held front-camera smartphone selfie',poseValue:value}).action,/stand naturally/i); });
test("PR 14 phase4 pose standing_hand_on_neck registry coverage",()=>{ const value='standing_hand_on_neck'; const item=SELFIE_POSES.find((pose)=>pose.value===value); assert.equal(item?.prompt,'standing with one hand resting on the back of the neck in a relaxed stretch posture'); assert.equal(POSE_HAND_USAGE[value],1); assert.equal(compatibilitySnapshot('standing_selfie',compatibilityCatalogs).pose.some((pose)=>pose.value===value),true); assert.match(buildRealismPacket({sceneType:'front_selfie',requestedSceneType:'front_selfie',captureType:'subject-held front-camera smartphone selfie',poseValue:value}).action,/stand naturally/i); });
test("PR 14 phase4 pose seated_hands_on_lap registry coverage",()=>{ const value='seated_hands_on_lap'; const item=SELFIE_POSES.find((pose)=>pose.value===value); assert.equal(item?.prompt,'seated with both hands resting naturally on the lap, forearms relaxed, posture upright but not stiff'); assert.equal(POSE_HAND_USAGE[value],0); assert.equal(compatibilitySnapshot('seated_selfie',compatibilityCatalogs).pose.some((pose)=>pose.value===value),true); assert.match(buildRealismPacket({sceneType:'front_selfie',requestedSceneType:'front_selfie',captureType:'subject-held front-camera smartphone selfie',poseValue:value}).action,/remain naturally seated/i); });
test("PR 14 phase4 pose seated_hand_on_knee registry coverage",()=>{ const value='seated_hand_on_knee'; const item=SELFIE_POSES.find((pose)=>pose.value===value); assert.equal(item?.prompt,'seated with one hand resting on the knee, fingers relaxed, elbow bent naturally'); assert.equal(POSE_HAND_USAGE[value],1); assert.equal(compatibilitySnapshot('seated_selfie',compatibilityCatalogs).pose.some((pose)=>pose.value===value),true); assert.match(buildRealismPacket({sceneType:'front_selfie',requestedSceneType:'front_selfie',captureType:'subject-held front-camera smartphone selfie',poseValue:value}).action,/remain naturally seated/i); });
test("PR 14 phase4 pose standing_neutral_at_side registry coverage",()=>{ const value='standing_neutral_at_side'; const item=SELFIE_POSES.find((pose)=>pose.value===value); assert.equal(item?.prompt,'standing with the free arm relaxed at the side, natural hand position, no forced pose'); assert.equal(POSE_HAND_USAGE[value],0); assert.equal(compatibilitySnapshot('standing_selfie',compatibilityCatalogs).pose.some((pose)=>pose.value===value),true); assert.match(buildRealismPacket({sceneType:'front_selfie',requestedSceneType:'front_selfie',captureType:'subject-held front-camera smartphone selfie',poseValue:value}).action,/stand naturally/i); });

test("PR 14 phase4 styling thobe_with_shemagh presence and injection",()=>{ const item=CLOTHING_STYLING.thobe.find((option)=>option.value==='thobe_with_shemagh'); assert.deepEqual(item?.garmentTags,['thobe','headwear']); const r=generateImagePrompt({sceneType:'front_selfie',clothingValue:'white_thobe',clothingStyling:'thobe_with_shemagh'}); assert.match(r.prompt,/traditional red-and-white shemagh/i); });
test("PR 14 phase4 styling shirt_fully_buttoned presence and injection",()=>{ const item=CLOTHING_STYLING.shirt.find((option)=>option.value==='shirt_fully_buttoned'); assert.deepEqual(item?.garmentTags,['shirt']); const r=generateImagePrompt({sceneType:'front_selfie',clothingValue:'look-01',clothingStyling:'shirt_fully_buttoned'}); assert.match(r.prompt,/fully buttoned to the collar/i); });
test("PR 14 phase4 styling shirt_under_jacket presence and injection",()=>{ const item=CLOTHING_STYLING.shirt.find((option)=>option.value==='shirt_under_jacket'); assert.deepEqual(item?.garmentTags,['shirt','jacket']); const r=generateImagePrompt({sceneType:'front_selfie',clothingValue:'look-01',clothingStyling:'shirt_under_jacket'}); assert.match(r.prompt,/structured blazer/i); });
test("PR 14 phase4 styling shirt_collar_up presence and injection",()=>{ const item=CLOTHING_STYLING.shirt.find((option)=>option.value==='shirt_collar_up'); assert.deepEqual(item?.garmentTags,['shirt']); const r=generateImagePrompt({sceneType:'front_selfie',clothingValue:'look-01',clothingStyling:'shirt_collar_up'}); assert.match(r.prompt,/collar raised naturally/i); });
test("PR 14 phase4 styling tshirt_with_overshirt presence and injection",()=>{ const item=CLOTHING_STYLING.tshirt.find((option)=>option.value==='tshirt_with_overshirt'); assert.deepEqual(item?.garmentTags,['tshirt','overshirt']); const r=generateImagePrompt({sceneType:'front_selfie',clothingValue:'white_tshirt',clothingStyling:'tshirt_with_overshirt'}); assert.match(r.prompt,/unbuttoned overshirt/i); });
test("PR 14 phase4 styling suit_jacket_on_shoulder presence and injection",()=>{ const item=CLOTHING_STYLING.suit.find((option)=>option.value==='suit_jacket_on_shoulder'); assert.deepEqual(item?.garmentTags,['suit','jacket']); const r=generateImagePrompt({sceneType:'front_selfie',clothingValue:'suit-navy-white',clothingStyling:'suit_jacket_on_shoulder'}); assert.match(r.prompt,/draped over one shoulder/i); });

test("PR 14 phase4 hand interaction tuck-shirt presence injection and usage",()=>{ const value='tuck-shirt'; const item=HAND_INTERACTIONS.find((option)=>option.value===value); assert.equal(item?.prompt,'one hand naturally tucking the shirt into the waistband'); assert.equal(getRemainingHands('front_selfie','subject-held front-camera smartphone selfie','none','',value),0); assert.match(generateImagePrompt({sceneType:'front_selfie',clothingValue:'look-01',handInteraction:value}).prompt,/tucking the shirt into the waistband/i); });
test("PR 14 phase4 hand interaction touch-watch presence injection and usage",()=>{ const value='touch-watch'; const item=HAND_INTERACTIONS.find((option)=>option.value===value); assert.equal(item?.prompt,'free hand lightly touching the wristwatch on the opposite wrist'); assert.equal(getRemainingHands('front_selfie','subject-held front-camera smartphone selfie','none','',value),0); assert.match(generateImagePrompt({sceneType:'front_selfie',clothingValue:'look-01',handInteraction:value}).prompt,/touching the wristwatch/i); });
test("PR 14 phase4 hand interaction adjust-glasses presence injection and usage",()=>{ const value='adjust-glasses'; const item=HAND_INTERACTIONS.find((option)=>option.value===value); assert.equal(item?.prompt,'one hand adjusting the glasses frame at the temple'); assert.equal(getRemainingHands('front_selfie','subject-held front-camera smartphone selfie','none','',value),0); assert.match(generateImagePrompt({sceneType:'front_selfie',clothingValue:'look-01',handInteraction:value}).prompt,/adjusting the glasses frame/i); });
test("PR 14 phase4 hand interaction hand-on-chest presence injection and usage",()=>{ const value='hand-on-chest'; const item=HAND_INTERACTIONS.find((option)=>option.value===value); assert.equal(item?.prompt,'one hand resting flat on the upper chest, calm and composed'); assert.equal(getRemainingHands('front_selfie','subject-held front-camera smartphone selfie','none','',value),0); assert.match(generateImagePrompt({sceneType:'front_selfie',clothingValue:'look-01',handInteraction:value}).prompt,/resting flat on the upper chest/i); });
test("PR 14 phase4 hand interaction scratch-beard presence injection and usage",()=>{ const value='scratch-beard'; const item=HAND_INTERACTIONS.find((option)=>option.value===value); assert.equal(item?.prompt,'one hand lightly touching the beard along the jawline'); assert.equal(getRemainingHands('front_selfie','subject-held front-camera smartphone selfie','none','',value),0); assert.match(generateImagePrompt({sceneType:'front_selfie',clothingValue:'look-01',handInteraction:value}).prompt,/touching the beard along the jawline/i); });

test("PR 14 phase4 abaya styling category is absent and UI options are disabled by emptiness",async()=>{ assert.equal(Object.hasOwn(CLOTHING_STYLING,'abaya'),false); const { clothingStylingOptionsForValue }=await import('../app.js'); assert.deepEqual(clothingStylingOptionsForValue('black_abaya'),[]); });
test("PR 14 phase4 clothing styling contains no tie-related option",()=>{ const metadata=Object.values(CLOTHING_STYLING).flat().map(({value,label})=>`${value} ${label}`).join(' '); assert.doesNotMatch(metadata,/\btie\b|necktie|ربطة|كرفتة/i); });

test("PR 14 phase4 furniture standing_hands_clasped_front stays generic",()=>{ const r=generateImagePrompt({sceneType:'direct_elevator_selfie',location:'inside an ordinary residential elevator in Saudi Arabia',poseValue:'standing_hands_clasped_front'}); assert.deepEqual(furnitureKinds(r.prompt),['generic']); assert.equal(r.validation.valid,true,r.validation.errors.join(' | ')); });
test("PR 14 phase4 furniture remaining standing poses stay generic",()=>{ for(const poseValue of ['standing_thumb_in_pocket','standing_hand_on_neck','standing_neutral_at_side']){ const r=generateImagePrompt({sceneType:'direct_elevator_selfie',location:'inside an ordinary residential elevator in Saudi Arabia',poseValue}); assert.deepEqual(furnitureKinds(r.prompt),['generic'],poseValue); assert.equal(r.validation.valid,true,r.validation.errors.join(' | ')); } });
test("PR 14 phase4 furniture seated_hands_on_lap uses chair",()=>{ const r=generateImagePrompt({sceneType:'cafe_selfie',location:'inside an ordinary Saudi cafe',poseValue:'seated_hands_on_lap'}); assert.deepEqual(furnitureKinds(r.prompt),['chair']); assert.equal(r.validation.valid,true,r.validation.errors.join(' | ')); });
test("PR 14 phase4 furniture seated_hand_on_knee uses chair",()=>{ const r=generateImagePrompt({sceneType:'cafe_selfie',location:'inside an ordinary Saudi cafe',poseValue:'seated_hand_on_knee'}); assert.deepEqual(furnitureKinds(r.prompt),['chair']); assert.equal(r.validation.valid,true,r.validation.errors.join(' | ')); });

test("PR 14 phase4 regression standing_hands_clasped_front keeps one free hand",()=>{ assert.equal(POSE_HAND_USAGE.standing_hands_clasped_front,0); assert.equal(getRemainingHands('front_selfie','subject-held front-camera smartphone selfie','none','standing_hands_clasped_front'),1); });
test("PR 14 phase4 regression seated_hand_on_knee consumes one hand",()=>{ assert.equal(POSE_HAND_USAGE.seated_hand_on_knee,1); assert.equal(getRemainingHands('front_selfie','subject-held front-camera smartphone selfie','none','seated_hand_on_knee'),0); });
