export const BEDROOM_REBUILD_ANCHOR = Object.freeze({
  room: 'A single fixed wide master bedroom, approximately 5.4 m LEFT-to-RIGHT by 6.2 m FRONT-to-BACK, with cream-painted walls, crown molding, glossy light-beige tile flooring, and one stable furniture layout reused in every bedroom image. The real wall-to-wall dimensions are spacious; never fake width by using an extreme ultra-wide viewpoint.',
  coordinate_frame: 'Use one immutable room coordinate frame with explicit depth and width: LEFT wall = bed/headboard zone plus the entrance door toward the front; RIGHT wall = wardrobe and dresser zone; BACK wall = fully closed dark curtains; FRONT wall = high split air conditioner. Preserve a clearly wider cross-room span than the bed-to-wardrobe gap and keep parallel wall lines converging toward physically consistent vanishing points. The room must read as a broad rectangular bedroom, never as a narrow corridor or tunnel.',
  bed: 'A low-profile king-size bed with an approximately 180 x 200 cm mattress is fixed along the LEFT wall in the LEFT-side bed zone. One continuous dark tufted headboard in dark charcoal upholstery is physically attached to the bed and is visibly wider than the mattress by a small realistic margin. The mattress has normal residential thickness and a continuous rectangular footprint; the upholstered frame remains distinct from the mattress. Grey cotton bedding stays on the same bed. The bed must read unmistakably as a full-width bed, never as a narrow bench, daybed, elongated strip, or perspective-stretched platform. Whenever framing exposes enough mattress, preserve a clear width cue from the far mattress edge, pillow span, or headboard width. Exactly one nightstand exists beside the headboard; the bed, headboard, mattress and nightstand never migrate, rotate, duplicate or change size.',
  wardrobe_mirror: 'The sliding wardrobe panels are genuine clear reflective mirrors, not smoked glass, black glass, transparent glazing, or dark decorative panels. Their brightness follows the room illumination and their reflections must visibly carry perspective-consistent portions of the bed, curtains, rug, dresser, ceiling lights, or subject where those elements fall inside the reflected field of view. Preserve straight panel boundaries and physically correct left-right reversal without duplicated people or furniture.',
  rug: 'One broad rectangular low-pile beige rug occupies the open floor zone between the bed and wardrobe. It is approximately 2.2 x 3.0 m, aligned with the room axes, visibly broad across the aisle, and never rendered as a thin runner. Keep its edges flat, its footprint separate from the bed frame and wardrobe track, and its perspective consistent with the tile grout lines.',
  circulation: 'Preserve a genuinely spacious circulation zone between the bed and RIGHT-wall storage. Keep at least about 1.4 m of clear usable walking width at the tightest bed-to-storage passage and substantially more open floor where the layout allows it. Do not squeeze the room into a long narrow aisle, do not push the wardrobe toward the bed, and do not enlarge furniture to consume the widened room.',
  lighting: 'For ordinary night bedroom lighting, recessed ceiling spots produce directional top-down pools and gradients while the single bedside lamp produces a localized warmer side pool. Preserve their different local white-balance contributions, inverse-distance falloff, occlusion and shadow direction. The face may retain partial natural shadow; exposure/HDR must not equalize both sides into invisible frontal fill. Mirrors reflect only light that physically reaches them.',
  fixed_layout_rule: 'IMPORTANT: This is one locked wide bedroom, not a generic bedroom category. Keep the same wide room dimensions, bed zone, single king-size bed, attached headboard, single nightstand, fixed bedroom chair, RIGHT-wall wardrobe, separate dresser, fully closed back-wall curtains, front-wall air conditioner, ceiling-light grid, broad rug, material palette and fixed daily-item zones in every bedroom image. Do not move, add, remove, resize, rotate, mirror, duplicate or substitute these elements. Do not add a second nightstand, second chair, sofa, desk, television, freestanding mirror or visible window. Camera framing may hide an element but must never make the room narrower, turn the bed into a bench, convert the rug into a runner, or replace reflective wardrobe mirrors with dark glass.'
});

export const REFERENCE_EXPRESSION_RULE = 'REFERENCE EXPRESSION SEPARATION: A reference image defines identity only. Do not copy its smile, mouth shape, gaze direction, eyelid tension, cheek activation, head pose or emotional expression unless the selected expression explicitly requests the same state. The selected expression in this prompt overrides the reference expression while identity remains unchanged.';

const LAPTOP_BED_POSE = 'seated naturally near the middle-left portion of the fixed king-size bed with the pelvis and upper thighs creating one broad connected mattress-compression zone; the torso remains supported by the seated base with a relaxed spine and no unsupported lean. An open laptop is centered across BOTH upper thighs, not on the mattress in front and not near the bed edge. The laptop base spans the thighs with broad gravity-supported contact, its center of mass stays inside the thigh support polygon, and the screen hinge sits near the knees rather than the abdomen. The screen opens to a physically usable angle of approximately 100–115 degrees toward the face. The free forearm approaches the keyboard from a relaxed elbow position; the wrist stays nearly neutral and the fingertips make light individual-key contact without hovering, merging or bending backward. The other hand alone holds the phone.';

const LAPTOP_BED_CAMERA = 'subject-held front camera at true eye level while seated on the bed, approximately 45–60 cm from the face, offset laterally only about 5–15 cm with pitch kept within roughly ±5 degrees of horizontal. The phone remains outside the captured frame. Use only mild arm-length wide-angle perspective: the phone-bearing shoulder may sit slightly forward, but the forearm must not become grossly enlarged, elongated, or wider than anatomically plausible. Keep enough lower-frame context to show stable laptop-to-both-thigh contact without turning the selfie into a high-angle downward shot.';

const LAPTOP_CONTACT_PHYSICS = 'LAPTOP / BODY CONTACT: The laptop base is supported by both thighs with no floating corner and no single-point balancing. Thigh soft tissue and shorts compress subtly under the chassis footprint. The base stays roughly transverse to the pelvis rather than rotated into a steep diagonal. The screen hinge torque is believable, the display does not outweigh the base, and the laptop does not appear to slide off the knees. The free wrist aligns with the keyboard plane and each visible finger remains anatomically separate.';
const AUTHORITATIVE_ROOM_SCALE = 'AUTHORITATIVE BEDROOM SCALE: The rebuilt dimensions in this section are controlling. The room is approximately 5.4 m by 6.2 m and the mattress is approximately 180 x 200 cm. If any inherited legacy room-scale sentence elsewhere in the composed prompt mentions a 160 x 200 cm bed, treat that legacy dimension as obsolete and do not render it. Preserve the 180 x 200 cm king-size geometry and the widened circulation clearances.';
const BED_PROPORTION_PHYSICS = 'BED / ROOM PROPORTION: Maintain the full 180 cm mattress width, normal mattress thickness, attached headboard width, broad open floor zone and wide bed-to-wardrobe clearance under perspective. A close selfie may crop part of the bed, but visible bed edges must still imply a full king-size rectangle rather than a narrow bench or endless strip.';

export function bedroomPoseOverride(poseValue = '', fallbackPose = '') {
  return poseValue === 'bedroom-laptop-bed' ? LAPTOP_BED_POSE : fallbackPose;
}

export function bedroomCameraOverride(poseValue = '', fallbackCamera = '') {
  return poseValue === 'bedroom-laptop-bed' ? LAPTOP_BED_CAMERA : fallbackCamera;
}

export function bedroomPhysicsOverrides(poseValue = '') {
  const rules = [AUTHORITATIVE_ROOM_SCALE, BED_PROPORTION_PHYSICS, BEDROOM_REBUILD_ANCHOR.lighting];
  if (poseValue === 'bedroom-laptop-bed') rules.push(LAPTOP_CONTACT_PHYSICS);
  return rules;
}
