export const BEDROOM_REBUILD_ANCHOR = Object.freeze({
  room: 'A single fixed spacious rectangular lived-in master bedroom reconstructed from the supplied room reference. The room is clearly longer FRONT-to-BACK than it is wide, with generous real floor area and circulation space, warm cream-to-taupe walls, layered crown molding and a stepped tray ceiling, glossy light-beige large-format tile flooring, and one stable furniture layout reused in every bedroom image. Do not invent exact metric room dimensions from the single reference photograph, and never fake spaciousness with extreme ultra-wide distortion, stretched walls, miniaturized furniture, or an artificially enlarged field of view.',
  coordinate_frame: 'Use one immutable room coordinate frame: FRONT = entrance and camera-end of the room; BACK = the wall covered by fully closed black-to-charcoal curtains; LEFT wall = the bed/headboard zone plus the high wall-mounted split air conditioner; RIGHT wall = the long dark-wood wardrobe/storage run and front-right dresser zone. The entrance door remains at the front-left edge. Preserve corner order, wall-to-wall proportions, object scale, tile-grid perspective, and vanishing directions across every view. The room must read as one broad residential bedroom with a large open central floor zone, never as a narrow corridor or tunnel.',
  bed: 'A large low-profile full-width residential bed is fixed against the LEFT wall, with one continuous dark charcoal upholstered headboard made of broad horizontal padded channels. The mattress projects inward from the left wall as one continuous rectangular support surface with normal residential thickness; the upholstered base remains physically distinct from the mattress. Grey bedding stays on this same bed with natural rumpling, gravity folds and ordinary daily-use disorder. Clothing may lie casually on the bedding in stable lived-in zones. The bed must read unmistakably as a broad adult bed, never as a narrow bench, daybed, strip, shelf, or perspective-stretched platform. Whenever enough mattress is visible, preserve clear width cues from the pillow span, far mattress edge, headboard span, bedding spread and mattress-to-floor footprint. Exactly one primary dark-wood nightstand remains beside the headboard zone.',
  wardrobe_mirror: 'The RIGHT wall carries a long dark-wood built-in storage system composed of tall reflective or mirrored panels together with open hanging bays, shelves and drawers. Do not simplify the entire run into featureless black glass or into identical full-height mirror doors. Reflective panels must show perspective-consistent portions of the real room only when those elements fall inside the reflection cone, with straight panel boundaries, preserved frame divisions and physically correct left-right reversal. Open bays keep believable depth, hanging garments, drawer fronts and shelf occlusion.',
  rug: 'One large broad rectangular beige-to-greige low-pile rug occupies the open central-front floor zone. It is aligned with the room axes, surrounded by visible glossy tile on all sides, and reads as a substantial area rug rather than a narrow runner. Keep its edges flat, its footprint independent from the bed and right-wall storage, and its perspective consistent with the tile grout grid.',
  circulation: 'Preserve the visibly generous central circulation area from the entrance toward the back curtains, with a clear walking path between the LEFT-wall bed and the RIGHT-wall storage. The room should feel spacious because of real floor area, furniture spacing, exposed tile and usable passage width, not because of lens exaggeration. Do not push the wardrobe toward the bed, enlarge furniture to consume the aisle, stretch the room into a tunnel, or compress the central floor zone.',
  lighting: 'The stepped ceiling contains multiple small recessed circular downlights distributed around the perimeter and inner ceiling zones rather than a fixed six-light grid. Their physical fixture locations stay stable, but their on/off state may vary by lighting profile. In the supplied reference most fixtures are dark while only a small subset is illuminated, producing localized top-down pools, deep falloff, bright specular reflections on the glossy tile and dark rear/right-wall zones. The bedside lamp physically exists but may remain off. Do not invent frontal fill, ring light, studio softbox light, uniform ambient brightness, or physically impossible illumination. Phone-screen-only scenes must override all room practical lights and leave the ceiling spots and bedside lamp off.',
  fixed_layout_rule: 'AUTHORITATIVE REFERENCE LAYOUT: This supplied room reference controls the bedroom geometry. Keep the same FRONT entrance, BACK curtain wall, LEFT-wall bed and horizontally channeled dark headboard, high LEFT-wall split air conditioner, one primary nightstand with bedside lamp, one compact chair positioned near the BACK curtains slightly right of center with casually draped clothing, long RIGHT-wall dark-wood storage run with reflective panels plus open hanging and drawer sections, separate front-right dark-wood dresser/chest, broad central beige rug, glossy light-beige tiled floor and stable lived-in clutter zones. Keep a dark soft bag near the back/right storage-curtain area and allow several naturally scattered footwear pairs around the rug and adjacent tile, matching the reference rather than locking the room to exactly two pairs. Do not add a second bed, sofa, desk, television, freestanding mirror, visible window, extra air conditioner or duplicate chair. If any inherited legacy bedroom sentence conflicts by placing the air conditioner on the FRONT wall, the chair on the FRONT wall, limiting the ceiling to six spots, forcing exactly two shoe pairs, claiming a narrow 4 m x 5 m room, or forcing a 160 x 200 cm queen bed, treat that legacy wording as obsolete. Camera framing may hide an element but must never relocate, replace, mirror, duplicate or redesign it.'
});

export const REFERENCE_EXPRESSION_RULE = 'REFERENCE EXPRESSION SEPARATION: A reference image defines identity only. Do not copy its smile, mouth shape, gaze direction, eyelid tension, cheek activation, head pose or emotional expression unless the selected expression explicitly requests the same state. The selected expression in this prompt overrides the reference expression while identity remains unchanged.';

const LAPTOP_BED_POSE = 'seated naturally near the middle-left portion of the fixed large bed with the pelvis and upper thighs creating one broad connected mattress-compression zone; the torso remains supported by the seated base with a relaxed spine and no unsupported lean. An open laptop is centered across BOTH upper thighs, not on the mattress in front and not near the bed edge. The laptop base spans the thighs with broad gravity-supported contact, its center of mass stays inside the thigh support polygon, and the screen hinge sits near the knees rather than the abdomen. The screen opens to a physically usable angle of approximately 100–115 degrees toward the face. The free forearm approaches the keyboard from a relaxed elbow position; the wrist stays nearly neutral and the fingertips make light individual-key contact without hovering, merging or bending backward. The other hand alone holds the phone.';

const LAPTOP_BED_CAMERA = 'subject-held front camera at true eye level while seated on the bed, approximately 45–60 cm from the face, offset laterally only about 5–15 cm with pitch kept within roughly ±5 degrees of horizontal. The phone remains outside the captured frame. Use only mild arm-length wide-angle perspective: the phone-bearing shoulder may sit slightly forward, but the forearm must not become grossly enlarged, elongated, or wider than anatomically plausible. Keep enough lower-frame context to show stable laptop-to-both-thigh contact without turning the selfie into a high-angle downward shot.';

const LAPTOP_CONTACT_PHYSICS = 'LAPTOP / BODY CONTACT: The laptop base is supported by both thighs with no floating corner and no single-point balancing. Thigh soft tissue and shorts compress subtly under the chassis footprint. The base stays roughly transverse to the pelvis rather than rotated into a steep diagonal. The screen hinge torque is believable, the display does not outweigh the base, and the laptop does not appear to slide off the knees. The free wrist aligns with the keyboard plane and each visible finger remains anatomically separate.';
const AUTHORITATIVE_ROOM_GEOMETRY = 'AUTHORITATIVE BEDROOM GEOMETRY: The supplied room reference is the controlling spatial source. Preserve a spacious rectangular room with greater front-to-back depth than width, a broad adult bed projecting inward from the LEFT wall, a large central open floor zone, a BACK wall of closed dark curtains, a high LEFT-wall split air conditioner, a chair near the back curtains, and the long RIGHT-wall storage system. Do not rely on unverified exact metric room or mattress dimensions from the single photograph. Any inherited legacy size, wall-placement, light-count or footwear-count sentence that conflicts with this observed-reference geometry is obsolete.';
const BED_PROPORTION_PHYSICS = 'BED / ROOM PROPORTION: Maintain a broad full-width adult mattress, normal mattress thickness, the attached horizontal-channel headboard, broad open floor zone and generous bed-to-storage clearance under perspective. A close selfie may crop part of the bed, but visible bed edges, pillows, bedding spread and support contact must still imply one full rectangular bed rather than a narrow bench or endless strip.';
const REFERENCE_ROOM_INVENTORY = 'REFERENCE ROOM INVENTORY: Preserve the layered tray ceiling and many recessed downlight fixtures, glossy tiled floor and grout continuity, large beige central rug, closed charcoal curtains, dark wood right-wall wardrobe/storage with reflective and open sections, front-right dresser, one primary nightstand with lamp and ordinary personal clutter, scattered footwear, clothing on the bed and chair, and a dark soft bag near the rear-right zone. The room is lived-in and imperfect, not showroom-clean.';

export function bedroomPoseOverride(poseValue = '', fallbackPose = '') {
  return poseValue === 'bedroom-laptop-bed' ? LAPTOP_BED_POSE : fallbackPose;
}

export function bedroomCameraOverride(poseValue = '', fallbackCamera = '') {
  return poseValue === 'bedroom-laptop-bed' ? LAPTOP_BED_CAMERA : fallbackCamera;
}

export function bedroomPhysicsOverrides(poseValue = '') {
  const rules = [AUTHORITATIVE_ROOM_GEOMETRY, BED_PROPORTION_PHYSICS, REFERENCE_ROOM_INVENTORY, BEDROOM_REBUILD_ANCHOR.lighting];
  if (poseValue === 'bedroom-laptop-bed') rules.push(LAPTOP_CONTACT_PHYSICS);
  return rules;
}
