import { CATALOG, REALISM_MODULES } from '../data/catalog.js';
import { normalizeState } from './state.js';
import { validationStatus } from './validation.js';
const byId=(field,id)=>(CATALOG[field]||[]).find(item=>item.id===id);
const promptOf=(field,id,custom='')=>{const option=byId(field,id);if(!option)return'';return option.id==='custom'?custom.trim():option.prompt;};
function subjectPrompt(state){return [`one primary subject, apparent age ${state.age}`,promptOf('pose',state.pose,state.customPose),promptOf('expression',state.expression),promptOf('hair',state.hair,state.customHair),promptOf('beard',state.beard,state.customBeard),promptOf('glasses',state.glasses,state.customGlasses),promptOf('clothing',state.clothing,state.customClothing)].filter(Boolean).join('; ');}
function realismPrompt(state){return REALISM_MODULES.filter(module=>state.modules[module.id]!=='off').map(module=>`${module.label} (${state.modules[module.id]}): ${module.prompt}`).join('\n- ');}
function locationPrompt(state){return promptOf('location',state.location,state.customLocation);}
function referencePrompt(state){return state.referenceRole==='none'?promptOf('referenceRole','none'):promptOf('referenceRole',state.referenceRole);}
export function compileDetailed(input={}){
 const state=normalizeState(input);const status=validationStatus(state);if(status.blocked)return`OUTPUT BLOCKED BY PHYSICS VALIDATION\n${status.issues.filter(i=>i.severity!=='warning').map(i=>`- ${i.code}: ${i.message}`).join('\n')}`;const light=promptOf('lightSource',state.lightSource,state.customLightSource);
 return ['GENERATE ONE PHOTOREALISTIC IMAGE — PHYSICS PROMPT STUDIO','',`SCENE INTENT: ${state.idea.trim()||'natural realistic everyday scene'}`,`LOCATION: ${locationPrompt(state)}. Keep it ordinary and non-iconic; no recognizable landmark or named venue.`,`TIME: ${promptOf('time',state.time)}.`,`CAPTURE TYPE LOCK: ${promptOf('captureType',state.captureType)}. Never silently change the capture type.`,`CAMERA GEOMETRY: ${promptOf('framing',state.framing)}; ${state.focalLength}mm equivalent; optical subject distance ${state.distance}cm; yaw ${state.yaw}°; pitch ${state.pitch}°; roll ${state.roll}°; aspect ratio ${promptOf('ratio',state.ratio)}. These numeric values are authoritative.`,`SUBJECT: ${subjectPrompt(state)}.`,`REFERENCE: ${referencePrompt(state)}.`,`PHYSICAL LIGHTING: ${light}; direction ${promptOf('lightDirection',state.lightDirection)}; falloff ${promptOf('lightFalloff',state.lightFalloff)}. Light must obey occlusion, distance, surface orientation and source size.`,`CAMERA PROCESSING: ${promptOf('exposure',state.exposure)}; ${promptOf('hdr',state.hdr)}; ${promptOf('whiteBalance',state.whiteBalance)}. Processing may reveal captured signal but must never create illumination, highlights, shadows or reflections without a physical source.`,`REALISM MODULES:\n- ${realismPrompt(state)}`,'ENVIRONMENTAL INTERACTION: gravity, contact pressure, clothing folds, hair response, floor contact, shadows and reflections must agree with the scene. Background objects must have plausible scale, placement and depth.','CONTROLLED IMPERFECTION: preserve realistic sensor noise, mild edge softness, small exposure/WB imperfections and natural asymmetry. No studio polish unless explicitly requested.',state.notes.trim()?`USER NOTES: ${state.notes.trim()}`:'','','FINAL FORENSIC QA: reject impossible anatomy, floating contact, physically unsupported light, inconsistent reflection geometry, impossible perspective, duplicated features, background scale errors, or capture-type violations before finalizing.'].filter(Boolean).join('\n');
}
export function compileConcise(input={}){const state=normalizeState(input);const status=validationStatus(state);if(status.blocked)return compileDetailed(state);return ['Photorealistic image.',state.idea.trim(),locationPrompt(state),promptOf('time',state.time),promptOf('captureType',state.captureType),promptOf('framing',state.framing),`${state.focalLength}mm eq, ${state.distance}cm, yaw ${state.yaw}°, pitch ${state.pitch}°, roll ${state.roll}°, ${state.ratio}`,subjectPrompt(state),`Physical light only: ${promptOf('lightSource',state.lightSource,state.customLightSource)}, ${promptOf('lightDirection',state.lightDirection)}, ${promptOf('lightFalloff',state.lightFalloff)}.`,'Exposure/HDR/WB may process captured signal only and cannot invent light. Correct anatomy, contacts, materials, reflections, atmospheric depth and restrained camera imperfections.'].filter(Boolean).join(' ');}
export function compileNegative(){return'no impossible anatomy, no extra fingers, no duplicated limbs, no floating objects, no unsupported reflections, no fake rim light, no invented illumination, no studio light unless requested, no excessive skin smoothing, no plastic skin, no impossible bokeh, no inconsistent perspective, no recognizable landmark, no named venue, no cinematic grading by default';}
export function compileJson(input={}){const state=normalizeState(input);const status=validationStatus(state);return JSON.stringify({version:'main-v5',domain:'general-scenes',deterministic:true,state,validation:status,outputs:{detailed:compileDetailed(state),concise:compileConcise(state),negative:compileNegative(state)}},null,2);}
