export const SAUDI_CULTURAL_DRESS_LOCK = 'CULTURAL CONTEXT — SAUDI: All women who appear in the frame must wear a plain black abaya. Adult women should also wear a black niqab covering everything except the eyes. Do not show exposed hair, uncovered female faces, or Western-style female clothing. Men may wear a white Saudi thobe, a bisht, or ordinary business attire (shirt and trousers). This rule applies to every Saudi location, indoor or outdoor, day or night.';

const grouped = (rows) => rows.map(([group, value, label, prompt]) => ({ group, value, label, prompt }));
const simple = (rows) => rows.map(([value, label, prompt]) => ({ value, label, prompt }));

export const SAUDI_LOCATIONS = grouped([
['مجالس ومنازل','modern_saudi_majlis','مجلس سعودي حديث وأنيق','inside a modern, lived-in Saudi Arabian majlis with realistic seating, circulation space, hospitality details, and no palace-like exaggeration'],
['مجالس ومنازل','traditional_majlis','مجلس سعودي تقليدي واقعي','inside a realistic traditional Saudi majlis with restrained heritage details, practical seating, and authentic lived-in proportions'],
['مجالس ومنازل','villa_living_room','صالة فيلا سعودية حديثة','inside a contemporary Saudi residential villa living room with believable furniture scale, warm neutral materials, and ordinary domestic details'],
['مجالس ومنازل','villa_driveway','مدخل فيلا سكنية','on the private driveway of a Saudi residential villa with realistic gate, boundary wall, paving, vehicle clearance, and ordinary neighborhood context'],
['مجالس ومنازل','villa_garage','كراج خاص لفيلا','inside a private residential villa garage in Saudi Arabia, not a commercial parking garage, with practical lighting and believable household storage'],
['مجالس ومنازل','rooftop_terrace','سطح / تراس منزل','on a residential rooftop terrace in Saudi Arabia with realistic parapets, utility elements, nearby roofs, and atmospheric depth'],
['مدن وأحياء','riyadh_residential','حي سكني في الرياض','on an ordinary residential street in Riyadh with contemporary villas, boundary walls, parked cars, sidewalks, asphalt, and no iconic landmark'],
['مدن وأحياء','riyadh_business','منطقة أعمال حديثة في الرياض','in a modern Riyadh business district with plausible office buildings, street furniture, traffic spacing, and non-iconic urban background'],
['مدن وأحياء','jeddah_residential','حي سكني في جدة','on a believable residential street in Jeddah with local apartment and villa architecture, parked vehicles, warm coastal atmosphere, and no landmark'],
['مدن وأحياء','jeddah_corniche','كورنيش جدة','along a believable Jeddah corniche setting with waterfront promenade, practical lighting, paving, railings, distant city lights, and realistic sea atmosphere'],
['مدن وأحياء','khobar_corniche','كورنيش الخبر','along Al Khobar waterfront with a realistic corniche promenade, palm landscaping, railings, parking, and physically plausible Gulf humidity'],
['مدن وأحياء','dammam_street','شارع حضري في الدمام','on an ordinary urban street in Dammam with practical storefronts, asphalt, curb geometry, parked cars, and believable Gulf-region atmosphere'],
['مدن وأحياء','makkah_residential','حي سكني في مكة','in a non-iconic residential district in Makkah with ordinary local buildings, roads, parked vehicles, and no holy-site depiction'],
['مدن وأحياء','madinah_residential','حي سكني في المدينة','in a non-iconic residential district in Madinah with ordinary local architecture, roads, sidewalks, and no holy-site depiction'],
['مدن وأحياء','taif_hills','منطقة مرتفعة في الطائف','in a Taif hillside urban area with realistic elevation changes, retaining walls, local roads, cooler mountain atmosphere, and ordinary buildings'],
['مدن وأحياء','abha_mountain_city','أبها الجبلية','in an Abha mountain-city setting with realistic slopes, regional vegetation, layered atmospheric depth, and ordinary urban architecture'],
['مدن وأحياء','tabuk_outskirts','أطراف تبوك','on the outskirts of Tabuk with low-rise development, broad roads, dry terrain, and realistic northern Saudi atmosphere'],
['ضيافة وأعمال','saudi_cafe','مقهى سعودي عادي','inside an ordinary contemporary Saudi cafe with practical ceiling lights, mixed seating, believable service details, and non-commercial candid atmosphere'],
['ضيافة وأعمال','specialty_coffee','مقهى قهوة مختصة','inside a contemporary Saudi specialty coffee shop with realistic counter layout, tables, ceiling fixtures, patrons, and practical material reflections'],
['ضيافة وأعمال','casual_restaurant','مطعم عائلي / كاجوال','inside a casual Saudi restaurant with believable table spacing, practical lights, restrained decor, and ordinary dinner occupancy'],
['ضيافة وأعمال','saudi_office','مكتب سعودي حديث','inside an ordinary modern Saudi office with practical workstations, neutral finishes, realistic ceiling lighting, and lived-in work details'],
['ضيافة وأعمال','real_estate_office','مكتب عقاري','inside a realistic Saudi real-estate office with desks, chairs, files, screens, practical lighting, and no showroom-like staging'],
['ضيافة وأعمال','hotel_lobby','لوبي فندق حديث','inside a contemporary Saudi hotel lobby with believable scale, guest circulation, practical fixtures, and restrained premium materials'],
['ضيافة وأعمال','mall_atrium','مول تجاري','inside a Saudi shopping mall atrium with realistic storefront spacing, escalators or walkways, mixed practical lighting, and naturally distributed visitors'],
['ضيافة وأعمال','barbershop','صالون حلاقة رجالي','inside an ordinary Saudi men’s barbershop with mirrors, chairs, counters, realistic ceiling lights, and naturally used work surfaces'],
['ضيافة وأعمال','gym','نادي رياضي','inside a modern Saudi gym with correctly scaled exercise equipment, practical overhead lighting, rubber flooring, and believable occupancy'],
['ضيافة وأعمال','airport_terminal','صالة مطار','inside a modern Saudi airport terminal with realistic wayfinding, seating, glazing, luggage behavior, and broad practical lighting'],
['تسوق','supermarket_aisle','ممر سوبرماركت','inside an ordinary Saudi supermarket aisle with correctly scaled shelving, mixed packaged goods, floor reflections, imperfect product alignment, and broad practical ceiling lighting'],
['تسوق','convenience_store','بقالة صغيرة','inside a neighborhood convenience store in Saudi Arabia with narrow aisles, refrigerated cases, counter clutter, stacked everyday goods, practical fluorescent light, and normal wear'],
['تسوق','grocery_store','متجر بقالة','inside an ordinary Saudi grocery store with shelves, produce bins, price tags, and practical ceiling lighting'],
['شوارع ومواقف','ordinary_saudi_street','شارع سعودي عادي','on an ordinary Saudi street with correct asphalt, curbs, sidewalks, utility elements, parked vehicles, and non-iconic buildings'],
['شوارع ومواقف','night_parking','موقف سيارات ليلي','in an ordinary Saudi outdoor parking area at night with marked bays, asphalt texture, wheel stops where appropriate, and localized LED pools of light'],
['شوارع ومواقف','day_parking','موقف سيارات نهاري','in an ordinary Saudi outdoor parking area in daylight with realistic painted markings, sun shadows, parked vehicles, and heat-haze where appropriate'],
['شوارع ومواقف','gas_station','محطة وقود','at a modern Saudi fuel station with canopy lighting, pumps, lane markings, convenience-store context, and correct safety clearances'],
['شوارع ومواقف','storefront_street','شارع محلات','on a Saudi commercial street with ordinary storefronts, signage kept secondary, curb parking, pedestrians, and practical shop lighting'],
['شوارع ومواقف','boulevard_walkway','ممشى حضري حديث','on a contemporary Saudi urban pedestrian boulevard with practical landscaping, paving, benches, storefront spill, and realistic crowd spacing'],
['طبيعة ورحلات','desert_roadside','طريق صحراوي','at a safe stopping area beside a Saudi desert road with correct road shoulder geometry, dry terrain, atmospheric depth, and sparse practical infrastructure'],
['طبيعة ورحلات','desert_dunes','كثبان رملية','in Saudi sand dunes with physically consistent wind-shaped ripples, realistic footprints or tire traces if present, and atmospheric depth'],
['طبيعة ورحلات','rocky_desert','صحراء صخرية','in a rocky Saudi desert landscape with natural stone variation, dry ground, realistic horizon haze, and no fantasy formations'],
['طبيعة ورحلات','alula_valley','وادي صحراوي بطابع العلا','in an AlUla-region desert valley with sandstone formations, dry ground, realistic scale, atmospheric depth, and no invented monumental structures'],
['طبيعة ورحلات','palm_farm','مزرعة نخيل','inside a Saudi palm farm with realistic rows, irrigation traces, soil, natural shade breakup, and ordinary agricultural details'],
['طبيعة ورحلات','mountain_viewpoint','إطلالة جبلية','at a Saudi mountain viewpoint with safe barriers or natural stopping area, layered terrain, realistic haze, and wind interaction'],
['طبيعة ورحلات','wadi','وادي طبيعي','in a natural Saudi wadi with dry or seasonally textured ground, rock layers, sparse vegetation, and realistic topography'],
['طبيعة ورحلات','red_sea_beach','شاطئ البحر الأحمر','on a Saudi Red Sea beach with physically plausible shoreline, wet-sand reflectance, sea haze, wind, and ordinary recreational context'],
['طبيعة ورحلات','gulf_beach','شاطئ الخليج','on a Saudi Arabian Gulf beach with calm coastal water, humidity haze, realistic sand, shoreline reflections, and ordinary waterfront context'],
['طبيعة ورحلات','public_park','حديقة عامة','inside a Saudi public park with practical paths, benches, irrigation-aware landscaping, family-use context, and realistic lighting']
]);

export const CLOTHING_OPTIONS = grouped([
['ثياب وتراث سعودي','white_thobe','ثوب أبيض سعودي','a plain well-fitted white Saudi thobe with realistic cotton-poplin weight, natural folds, seam tension, and no artificial gloss'],
['ثياب وتراث سعودي','navy_thobe','ثوب كحلي داكن','a refined dark navy Saudi thobe with matte woven fabric, visible textile detail in lit areas, and natural compression folds'],
['ثياب وتراث سعودي','charcoal_thobe','ثوب فحمي','a charcoal Saudi thobe with realistic medium-weight fabric, restrained highlights, and naturally asymmetric folds'],
['ثياب وتراث سعودي','beige_thobe','ثوب بيج / رملي','a light beige Saudi thobe with realistic woven texture, soft drape, and practical warm-neutral tone'],
['ثياب وتراث سعودي','olive_thobe','ثوب زيتي هادئ','a muted olive Saudi thobe with matte textile response, natural sleeve creasing, and believable body compression'],
['ثياب وتراث سعودي','winter_thobe','ثوب شتوي ثقيل','a heavier winter Saudi thobe with denser fabric weight, broader folds, subdued sheen, and realistic gravity-driven drape'],
['ثياب وتراث سعودي','red_shemagh_agal','شماغ أحمر وأبيض مع عقال','a traditional red-and-white Saudi shemagh with a realistic black agal, natural woven thickness, gravity-driven asymmetric folds, and no turban-like wrapping'],
['ثياب وتراث سعودي','white_ghutra_agal','غترة بيضاء مع عقال','a traditional white Saudi ghutra with a realistic black agal, soft woven translucency, subtle asymmetry, and physically correct crown contact'],
['ثياب وتراث سعودي','red_shemagh_no_agal','شماغ أحمر بدون عقال','a red-and-white Saudi shemagh worn casually without an agal, with realistic woven folds and gravity-driven drape'],
['ثياب وتراث سعودي','white_ghutra_no_agal','غترة بيضاء بدون عقال','a white Saudi ghutra worn casually without an agal, with natural folds, soft fabric thickness, and realistic shoulder contact'],
['ثياب وتراث سعودي','bisht_thobe','ثوب مع بشت','a clean Saudi thobe worn with a lightweight formal bisht, with realistic shoulder support, long gravity-driven folds, subtle trim, restrained sheen, and natural sleeve openings'],
['ثياب وتراث سعودي','black_abaya','عباءة سوداء','a plain black abaya in matte medium-weight fabric with realistic shoulder drape, sleeve folds, hem weight, restrained highlights, and ordinary non-fashion-catalog styling'],
['ثياب وتراث سعودي','embroidered_abaya','عباءة سوداء بتطريز هادئ','a black abaya with restrained black-on-black embroidery, matte fabric response, realistic seam weight, gravity-driven folds, and no glossy ornamental exaggeration'],
['ثياب وتراث سعودي','abaya_hijab','عباءة سوداء مع حجاب','a plain black abaya with a black hijab, realistic layered fabric thickness, natural head-and-shoulder contact, matte textile response, and ordinary everyday drape'],
['كاجوال','black_tshirt','تيشيرت أسود سادة','a plain black crew-neck cotton T-shirt with matte jersey texture, body-conforming tension, and rounded natural folds'],
['كاجوال','white_tshirt','تيشيرت أبيض سادة','a plain white crew-neck cotton T-shirt with realistic jersey texture, soft folds, seam tension, and natural translucency control'],
['كاجوال','navy_tshirt','تيشيرت كحلي سادة','a plain navy cotton T-shirt with matte fabric response, natural shoulder drape, and realistic torso folds'],
['كاجوال','grey_tshirt','تيشيرت رمادي','a plain heather-grey cotton T-shirt with subtle knit variation, soft diffuse response, and believable folds'],
['كاجوال','navy_polo','بولو كحلي','a plain navy pique polo shirt with realistic knit texture, collar structure, small body folds, and restrained highlights'],
['كاجوال','white_polo','بولو أبيض','a plain white pique polo shirt with realistic knit texture, collar shape, seam tension, and natural folding'],
['كاجوال','charcoal_polo','بولو فحمي','a charcoal pique polo shirt with matte textile response, realistic collar behavior, and relaxed torso folds'],
['كاجوال','hoodie','هودي بسيط','a plain casual hoodie with medium-weight fleece, realistic hood volume, cuff compression, and gravity-driven folds'],
['كاجوال','crewneck_sweatshirt','سويت شيرت بدون قبعة','a plain crew-neck sweatshirt with medium-weight cotton fleece, ribbed cuffs, natural torso volume, and soft folds'],
['كاجوال','denim_jacket','جاكيت دنيم','a simple denim jacket with realistic structured cotton weave, seam stiffness, layered folds, and restrained worn texture'],
['كاجوال','light_jacket','جاكيت خفيف','a simple lightweight casual jacket with realistic shell fabric, zipper structure, cuff tension, and natural folds']
]);

export const FORMAL_SUITS = [
  { group: 'كلاسيكي', value: 'suit-navy-white', label: 'بدلة كحلية + قميص أبيض', prompt: 'a navy two-piece suit with a crisp white dress shirt, wool-blend texture, natural lapel roll, sleeve break, trouser crease, restrained sheen' },
  { group: 'كلاسيكي', value: 'suit-navy-lightblue', label: 'بدلة كحلية + قميص أزرق فاتح', prompt: 'a navy two-piece suit with a light-blue dress shirt, wool-blend texture, matte trouser drape' },
  { group: 'كلاسيكي', value: 'suit-charcoal-white', label: 'بدلة فحمية + قميص أبيض', prompt: 'a charcoal two-piece suit with a white dress shirt, visible wool weave, structured lapel roll' },
  { group: 'كلاسيكي', value: 'suit-charcoal-lightblue', label: 'بدلة فحمية + قميص أزرق فاتح', prompt: 'a charcoal two-piece suit with a light-blue dress shirt, restrained matte finish' },
  { group: 'كلاسيكي', value: 'suit-black-white', label: 'بدلة سوداء + قميص أبيض', prompt: 'a black two-piece suit with a white dress shirt, high contrast, natural fabric folds' },
  { group: 'كلاسيكي', value: 'suit-black-black', label: 'بدلة سوداء + قميص أسود', prompt: 'a black two-piece suit with a black dress shirt, monochromatic, matte texture' },
  { group: 'كلاسيكي', value: 'suit-grey-light', label: 'بدلة رمادية فاتحة + قميص أبيض', prompt: 'a light-grey two-piece suit with a white dress shirt, cool palette, wool-blend texture' },
  { group: 'كلاسيكي', value: 'suit-grey-mid', label: 'بدلة رمادية متوسطة + قميص أبيض', prompt: 'a mid-grey two-piece suit with a white dress shirt, balanced neutral palette' },
  { group: 'أعمال', value: 'suit-navy-pinstripe', label: 'بدلة كحلية مخطط رفيع + قميص أبيض', prompt: 'a navy pinstripe two-piece suit with a white shirt, subtle white lines, tailored structure' },
  { group: 'أعمال', value: 'suit-charcoal-pinstripe', label: 'بدلة فحمية مخطط رفيع + قميص أبيض', prompt: 'a charcoal pinstripe two-piece suit with a white shirt, refined business silhouette' },
  { group: 'أعمال', value: 'suit-grey-check', label: 'بدلة رمادية كاروهات خفيفة + قميص أبيض', prompt: 'a light-grey suit with subtle windowpane check pattern, white shirt, wool-blend' },
  { group: 'أعمال', value: 'suit-blue-dark', label: 'بدلة زرقاء داكنة + قميص أزرق فاتح', prompt: 'a deep blue two-piece suit with a light-blue shirt, cool professional palette' },
  { group: 'أعمال', value: 'suit-brown-tobacco', label: 'بدلة بنية تبغي + قميص كريمي', prompt: 'a tobacco-brown two-piece suit with a cream shirt, warm office palette' },
  { group: 'أعمال', value: 'suit-olive', label: 'بدلة زيتية + قميص بيج', prompt: 'an olive two-piece suit with a beige shirt, muted professional palette' },
  { group: 'أعراس', value: 'suit-navy-velvet', label: 'بدلة كحلية + بليزر مخملي', prompt: 'a navy two-piece suit with a matching velvet blazer, white shirt, subtle velvet sheen on highlight-facing surfaces' },
  { group: 'أعراس', value: 'suit-charcoal-velvet', label: 'بدلة فحمية + بليزر مخملي', prompt: 'a charcoal suit with a matching velvet blazer, white shirt, rich fabric depth' },
  { group: 'أعراس', value: 'suit-burgundy-dark', label: 'بدلة عنابية داكنة + قميص كريمي', prompt: 'a deep burgundy two-piece suit with a cream shirt, warm celebration palette' },
  { group: 'أعراس', value: 'suit-cream-white', label: 'بدلة كريمية + قميص أبيض', prompt: 'a cream two-piece suit with a white shirt, warm light palette, restrained sheen' },
  { group: 'أعراس', value: 'suit-beige-light', label: 'بدلة بيج فاتحة + قميص بيج', prompt: 'a light beige two-piece suit with a matching beige shirt, tonal warm palette' },
  { group: 'أعراس', value: 'suit-grey-dark-midshirt', label: 'بدلة رمادية داكنة + قميص رمادي متوسط', prompt: 'a dark grey two-piece suit with a mid-grey shirt, monochromatic sophisticated' },
  { group: 'ترابي', value: 'suit-olive-dark', label: 'بدلة زيتية داكنة + قميص بيج', prompt: 'a dark olive two-piece suit with a beige shirt, muted earth palette' },
  { group: 'ترابي', value: 'suit-brown-dark', label: 'بدلة بنية داكنة + قميص كريمي', prompt: 'a dark brown two-piece suit with a cream shirt, deep warm palette' },
  { group: 'ترابي', value: 'suit-brown-tobacco-light', label: 'بدلة بنية تبغي فاتحة + قميص بيج', prompt: 'a light tobacco two-piece suit with a beige shirt, warm earth pairing' },
  { group: 'ترابي', value: 'suit-grey-earthy', label: 'بدلة رمادية ترابية + قميص بيج', prompt: 'an earthy grey two-piece suit with a beige shirt, muted natural palette' },
  { group: 'ترابي', value: 'suit-burgundy-classic', label: 'بدلة عنابية + قميص أبيض', prompt: 'a burgundy two-piece suit with a white shirt, rich deep palette' },
  { group: 'بليزر', value: 'blazer-navy-grey', label: 'بليزر كحلي + بنطال رمادي فاتح', prompt: 'a navy blazer with light-grey tailored trousers, smart-casual tailoring, natural lapel roll' },
  { group: 'بليزر', value: 'blazer-charcoal-navy', label: 'بليزر فحمي + بنطال كحلي', prompt: 'a charcoal blazer with navy tailored trousers, refined business-casual' },
  { group: 'بليزر', value: 'blazer-beige-tobacco', label: 'بليزر بيج + بنطال بني تبغي', prompt: 'a beige blazer with tobacco-brown trousers, warm earth-tone pairing' },
  { group: 'بليزر', value: 'blazer-grey-light-charcoal', label: 'بليزر رمادي فاتح + بنطال فحمي', prompt: 'a light-grey blazer with charcoal trousers, cool tonal contrast' },
  { group: 'بليزر', value: 'blazer-brown-cream', label: 'بليزر بني داكن + بنطال كريمي', prompt: 'a dark brown blazer with cream trousers, warm elegant pairing' }
];

export const FORMAL_LOOKS = simple([
['look-01','قميص أبيض + بنطال كحلي','a crisp white oxford cotton shirt with navy tailored wool-blend trousers, visible basket weave, matte trouser drape'],
['look-02','قميص أبيض + بنطال فحمي','a white oxford cotton shirt with charcoal tailored trousers, natural cotton wrinkles'],
['look-03','قميص أبيض + بنطال أسود','a white oxford cotton shirt with black tailored trousers, restrained contrast'],
['look-04','قميص أبيض + بنطال رمادي فاتح','a white oxford cotton shirt with light-grey tailored trousers'],
['look-05','قميص أبيض + بنطال رمادي متوسط','a white oxford cotton shirt with mid-grey tailored trousers'],
['look-06','قميص أبيض + بنطال كريمي','a white oxford cotton shirt with cream tailored trousers'],
['look-07','قميص أبيض + بنطال بيج','a white oxford cotton shirt with beige tailored trousers'],
['look-08','قميص أبيض + بنطال بني تبغي','a white oxford shirt with tobacco-brown tailored trousers'],
['look-09','قميص أبيض + بنطال كاكي','a white oxford cotton shirt with khaki cotton-twill trousers'],
['look-10','قميص أبيض + بنطال زيتي','a white oxford cotton shirt with olive cotton-twill trousers'],
['look-11','قميص أزرق فاتح + بنطال كحلي','a light-blue oxford cotton shirt with navy tailored trousers, visible basket weave'],
['look-12','قميص أزرق فاتح + بنطال فحمي','a light-blue oxford cotton shirt with charcoal tailored trousers'],
['look-13','قميص أزرق فاتح + بنطال أسود','a light-blue oxford cotton shirt with black tailored trousers'],
['look-14','قميص أزرق فاتح + بنطال رمادي فاتح','a light-blue oxford shirt with light-grey tailored trousers'],
['look-15','قميص أزرق فاتح + بنطال رمادي متوسط','a light-blue oxford shirt with mid-grey tailored trousers'],
['look-16','قميص أزرق فاتح + بنطال كريمي','a light-blue oxford shirt with cream tailored trousers'],
['look-17','قميص أزرق فاتح + بنطال بيج','a light-blue oxford shirt with beige tailored trousers'],
['look-18','قميص أزرق فاتح + بنطال بني تبغي','a light-blue oxford shirt with tobacco-brown tailored trousers'],
['look-19','قميص أزرق فاتح + بنطال كاكي','a light-blue oxford shirt with khaki chinos'],
['look-20','قميص أزرق فاتح + بنطال زيتي','a light-blue oxford shirt with olive chinos'],
['look-21','قميص أزرق فاتح + بنطال كحلي مخطط','a light-blue oxford shirt with navy pinstripe trousers'],
['look-22','قميص كحلي مخطط + بنطال فحمي','a navy pinstripe shirt with charcoal tailored trousers'],
['look-23','قميص كحلي مخطط + بنطال رمادي فاتح','a navy pinstripe shirt with light-grey tailored trousers'],
['look-24','قميص كحلي مخطط + بنطال بني تبغي','a navy pinstripe shirt with tobacco-brown tailored trousers'],
['look-25','قميص كحلي مخطط + بنطال كحلي','a navy pinstripe shirt with navy tailored trousers'],
['look-26','قميص كحلي + بنطال رمادي فاتح','a navy dress shirt with light-grey tailored trousers'],
['look-27','قميص كحلي + بنطال رمادي متوسط','a navy dress shirt with mid-grey tailored trousers'],
['look-28','قميص كحلي + بنطال كريمي','a navy dress shirt with cream tailored trousers'],
['look-29','قميص كحلي + بنطال بيج','a navy dress shirt with beige tailored trousers'],
['look-30','قميص كحلي + بنطال فحمي','a navy dress shirt with charcoal tailored trousers'],
['look-31','قميص كحلي + بنطال أسود','a navy dress shirt with black tailored trousers'],
['look-32','قميص كحلي + بنطال بني تبغي','a navy dress shirt with tobacco-brown tailored trousers'],
['look-33','قميص كحلي + بنطال كاكي','a navy dress shirt with khaki chinos'],
['look-34','قميص كحلي + بنطال زيتي','a navy dress shirt with olive chinos'],
['look-35','قميص كحلي بياقة دائرية + بنطال رمادي فاتح','a navy band-collar shirt with light-grey tailored trousers'],
['look-36','قميص كحلي بياقة دائرية + بنطال فحمي','a navy band-collar shirt with charcoal tailored trousers'],
['look-37','قميص فحمي + بنطال كحلي','a charcoal dress shirt with navy tailored trousers'],
['look-38','قميص فحمي + بنطال أسود','a charcoal dress shirt with black tailored trousers'],
['look-39','قميص فحمي + بنطال رمادي فاتح','a charcoal dress shirt with light-grey tailored trousers'],
['look-40','قميص فحمي + بنطال رمادي متوسط','a charcoal dress shirt with mid-grey tailored trousers'],
['look-41','قميص فحمي + بنطال كريمي','a charcoal dress shirt with cream tailored trousers'],
['look-42','قميص فحمي + بنطال بيج','a charcoal dress shirt with beige tailored trousers'],
['look-43','قميص فحمي + بنطال بني تبغي','a charcoal dress shirt with tobacco-brown tailored trousers'],
['look-44','قميص رمادي متوسط + بنطال كحلي','a mid-grey dress shirt with navy tailored trousers'],
['look-45','قميص رمادي متوسط + بنطال فحمي','a mid-grey dress shirt with charcoal tailored trousers'],
['look-46','قميص رمادي متوسط + بنطال أسود','a mid-grey dress shirt with black tailored trousers'],
['look-47','قميص رمادي متوسط + بنطال بني تبغي','a mid-grey dress shirt with tobacco-brown tailored trousers'],
['look-48','قميص رمادي فاتح + بنطال كحلي','a light-grey dress shirt with navy tailored trousers'],
['look-49','قميص رمادي فاتح + بنطال فحمي','a light-grey dress shirt with charcoal tailored trousers'],
['look-50','قميص أسود + بنطال أسود','a black dress shirt with black tailored trousers, matte finish'],
['look-51','قميص أسود + بنطال فحمي','a black dress shirt with charcoal tailored trousers'],
['look-52','قميص أسود + بنطال رمادي متوسط','a black dress shirt with mid-grey tailored trousers'],
['look-53','قميص أسود + بنطال رمادي فاتح','a black dress shirt with light-grey tailored trousers'],
['look-54','قميص أسود + بنطال كحلي','a black dress shirt with navy tailored trousers'],
['look-55','قميص أسود + بنطال كريمي','a black dress shirt with cream tailored trousers'],
['look-56','قميص أسود + بنطال بيج','a black dress shirt with beige tailored trousers'],
['look-57','قميص أسود + بنطال كاكي','a black dress shirt with khaki chinos'],
['look-58','قميص أسود + بنطال زيتي','a black dress shirt with olive chinos'],
['look-59','قميص بيج + بنطال بني تبغي','a beige dress shirt with tobacco-brown tailored trousers'],
['look-60','قميص بيج + بنطال كحلي','a beige dress shirt with navy tailored trousers'],
['look-61','قميص بيج + بنطال فحمي','a beige dress shirt with charcoal tailored trousers'],
['look-62','قميص بيج + بنطال كريمي','a beige dress shirt with cream tailored trousers'],
['look-63','قميص بيج + بنطال كاكي','a beige dress shirt with khaki chinos'],
['look-64','قميص بيج + بنطال زيتي','a beige dress shirt with olive chinos'],
['look-65','قميص بيج + بنطال رمادي فاتح','a beige dress shirt with light-grey tailored trousers'],
['look-66','قميص بيج + بنطال رمادي متوسط','a beige dress shirt with mid-grey tailored trousers'],
['look-67','قميص بيج + بنطال بني غامق','a beige dress shirt with dark-brown tailored trousers'],
['look-68','قميص كريمي + بنطال بني تبغي','a cream dress shirt with tobacco-brown tailored trousers'],
['look-69','قميص كريمي + بنطال كحلي','a cream dress shirt with navy tailored trousers'],
['look-70','قميص كريمي + بنطال فحمي','a cream dress shirt with charcoal tailored trousers'],
['look-71','قميص كريمي + بنطال بيج','a cream dress shirt with beige tailored trousers'],
['look-72','قميص كريمي + بنطال بني غامق','a cream dress shirt with dark-brown tailored trousers'],
['look-73','قميص كريمي + بنطال كاكي','a cream dress shirt with khaki chinos'],
['look-74','قميص بني تبغي + بنطال كريمي','a tobacco-brown dress shirt with cream tailored trousers'],
['look-75','قميص بني تبغي + بنطال بيج','a tobacco-brown dress shirt with beige tailored trousers'],
['look-76','قميص بني تبغي + بنطال كحلي','a tobacco-brown dress shirt with navy tailored trousers'],
['look-77','قميص بني تبغي + بنطال فحمي','a tobacco-brown dress shirt with charcoal tailored trousers'],
['look-78','قميص بني غامق + بنطال بيج','a dark-brown dress shirt with beige tailored trousers'],
['look-79','قميص بني غامق + بنطال كريمي','a dark-brown dress shirt with cream tailored trousers'],
['look-80','قميص زيتي + بنطال بني تبغي','an olive dress shirt with tobacco-brown tailored trousers'],
['look-81','قميص زيتي + بنطال كحلي','an olive dress shirt with navy tailored trousers'],
['look-82','قميص زيتي + بنطال كريمي','an olive dress shirt with cream tailored trousers'],
['look-83','قميص زيتي + بنطال بيج','an olive dress shirt with beige tailored trousers'],
['look-84','قميص زيتي + بنطال كاكي','an olive dress shirt with khaki chinos'],
['look-85','قميص زيتي + بنطال فحمي','an olive dress shirt with charcoal tailored trousers'],
['look-86','قميص أخضر مريمي + بنطال كحلي','a sage-green oxford shirt with navy tailored trousers'],
['look-87','قميص أخضر مريمي + بنطال فحمي','a sage-green oxford shirt with charcoal tailored trousers'],
['look-88','قميص أخضر مريمي + بنطال كريمي','a sage-green oxford shirt with cream tailored trousers'],
['look-89','قميص أخضر مريمي + بنطال بني تبغي','a sage-green oxford shirt with tobacco-brown tailored trousers'],
['look-90','قميص عنابي + بنطال كحلي','a burgundy dress shirt with navy tailored trousers'],
['look-91','قميص عنابي + بنطال فحمي','a burgundy dress shirt with charcoal tailored trousers'],
['look-92','قميص عنابي + بنطال أسود','a burgundy dress shirt with black tailored trousers'],
['look-93','قميص عنابي + بنطال رمادي متوسط','a burgundy dress shirt with mid-grey tailored trousers'],
['look-94','قميص عنابي + بنطال بني تبغي','a burgundy dress shirt with tobacco-brown tailored trousers'],
['look-95','قميص وردي فاتح + بنطال رمادي متوسط','a pale pink oxford shirt with mid-grey tailored trousers'],
['look-96','قميص وردي فاتح + بنطال فحمي','a pale pink oxford shirt with charcoal tailored trousers'],
['look-97','قميص وردي فاتح + بنطال بيج','a pale pink oxford shirt with beige chinos'],
['look-98','قميص وردي فاتح + بنطال كحلي','a pale pink oxford shirt with navy tailored trousers'],
['look-99','قميص وردي فاتح + بنطال كاكي','a pale pink oxford shirt with khaki chinos'],
['look-100','قميص بياقة صينية أبيض + بنطال كحلي','a white mandarin-collar shirt with navy tailored trousers'],
['look-101','قميص بياقة صينية بيج + بنطال كحلي','a beige mandarin-collar shirt with navy tailored trousers'],
['look-102','قميص بياقة صينية عنابي + بنطال كحلي','a burgundy mandarin-collar shirt with navy tailored trousers'],
['look-103','قميص بياقة دائرية رمادي + بنطال أسود','a grey band-collar shirt with black tailored trousers'],
['look-104','قميص كتان أبيض + بنطال بيج','a white linen shirt with beige trousers, summer pairing'],
['look-105','قميص كتان أبيض + بنطال كحلي','a white linen shirt with navy tailored trousers'],
['look-106','قميص كتان أزرق فاتح + بنطال بيج','a light-blue linen shirt with beige trousers'],
['look-107','قميص كتان أزرق فاتح + بنطال كحلي','a light-blue linen shirt with navy tailored trousers'],
['look-108','قميص كتان بيج + بنطال كحلي','a beige linen shirt with navy tailored trousers'],
['look-109','قميص كتان بيج + بنطال بني تبغي','a beige linen shirt with tobacco-brown tailored trousers'],
['look-110','قميص كتان كريمي + بنطال كحلي','a cream linen shirt with navy tailored trousers'],
['look-111','قميص كتان كحلي + بنطال بيج','a navy linen shirt with beige trousers'],
['look-112','قميص كتان كحلي + بنطال كريمي','a navy linen shirt with cream trousers'],
['look-113','قميص كتان رملي + بنطال كحلي','a sand linen shirt with navy tailored trousers'],
['look-114','قميص كتان رملي + بنطال زيتي','a sand linen shirt with olive chinos'],
['look-115','قميص كتان رملي + بنطال بيج','a sand linen shirt with beige trousers'],
['look-116','قميص كتان رملي + بنطال بني تبغي','a sand linen shirt with tobacco-brown tailored trousers'],
['look-117','قميص فحمي + بنطال بني غامق','a charcoal dress shirt with dark-brown tailored trousers'],
['look-118','قميص كحلي + بنطال بني غامق','a navy dress shirt with dark-brown tailored trousers'],
['look-119','قميص أزرق فاتح + بنطال بني غامق','a light-blue oxford shirt with dark-brown tailored trousers'],
['look-120','قميص بيج + بنطال بني فاتح','a beige dress shirt with light-brown tailored trousers']
]);

export const SELFIE_POSES = simple([
['standing_relaxed','واقف باسترخاء','standing naturally with relaxed weight distribution, mild shoulder asymmetry, and no rigid portrait pose'],
['standing_one_hand','واقف واليد الحرة مرتاحة','standing naturally while the free hand rests casually near the thigh, pocket area, or torso without deliberate posing'],
['walking_slow','يمشي ببطء','walking slowly while taking the selfie, with subtle gait asymmetry and mild motion consistency appropriate to the shutter'],
['holding_basket','يمسك سلة تسوق','holding a supermarket shopping basket naturally in the free hand with correct grip, wrist angle, arm load, and gravity while keeping the phone-bearing arm independent'],
['seated_sofa','جالس على كنبة / مجلس','seated comfortably with realistic pelvis support, cushion compression, mild torso rotation, and anatomically coherent thighs and knees'],
['seated_chair','جالس على كرسي','seated naturally on a chair with correct hip support, back contact where applicable, feet placement, and relaxed torso posture'],
['lean_wall','ميل خفيف على جدار','leaning lightly against a wall with visible contact physics, subtle shoulder tilt, and realistic body weight transfer'],
['lean_counter','ميل خفيف على طاولة / كاونتر','leaning lightly against a counter or table with correct forearm or hip contact and believable body support'],
['driver_seat','جالس في مقعد السائق','seated naturally in the driver seat of a stationary vehicle, with correct seat compression, steering-wheel relationship, and cabin geometry'],
['passenger_seat','جالس في مقعد الراكب','seated naturally in the front passenger seat of a stationary vehicle with correct cabin orientation and seat contact'],
['door_open_car','واقف بجانب باب سيارة مفتوح','standing beside an open vehicle door while personally holding the phone, with correct door clearance, body-car contact spacing, and selfie reach'],
['coffee_hand','يمسك كوب قهوة باليد الحرة','holding a small coffee cup naturally in the free hand with correct finger contact, wrist angle, and gravity'],
['adjust_clothing','يعدّل الملابس باليد الحرة','gently adjusting a small section of clothing with the free hand, creating realistic fabric tension and contact folds'],
['hand_on_head','اليد الحرة على الرأس','placing the free hand naturally on the head with anatomically correct elbow elevation, wrist orientation, and hair or headwear contact'],
['one_hand_pocket','اليد الحرة في الجيب','placing the free hand casually in a pocket with realistic elbow angle, cloth tension, and pocket deformation'],
['close_relaxed','وقفة قريبة وعفوية','a close relaxed selfie pose with natural neck, shoulder, and upper-torso asymmetry and no influencer-style posing']
]);

export const SELFIE_ANGLES = simple([
['eye_centered','مستوى العين — أمامي','front camera at approximately eye level, yaw 0°, pitch 0°, with a tiny natural handheld roll'],
['eye_three_quarter_left','ثلاثة أرباع من اليسار','front camera slightly lateral for a mild three-quarter selfie from the left side, preserving realistic arm reach and perspective asymmetry'],
['eye_three_quarter_right','ثلاثة أرباع من اليمين','front camera slightly lateral for a mild three-quarter selfie from the right side, preserving realistic arm reach and perspective asymmetry'],
['slightly_high_center','أعلى من العين قليلًا — أمامي','front camera only slightly above eye level with a gentle downward pitch, not overhead, with physically plausible arm reach'],
['slightly_high_three_quarter','أعلى قليلًا — ثلاثة أرباع','front camera slightly above eye level and mildly lateral, producing a realistic elevated three-quarter selfie without giant-head distortion'],
['slightly_low_center','أخفض قليلًا — أمامي','front camera slightly below eye level with a gentle upward pitch and realistic lower-angle smartphone perspective'],
['low_offcenter','زاوية منخفضة خارج المركز','front camera modestly below eye level and off-center, with plausible wrist position, shoulder displacement, and no extreme distortion'],
['high_offcenter','زاوية مرتفعة خارج المركز','front camera modestly above eye level and off-center, with slight downward pitch, diagonal background depth, and real arm-length geometry'],
['close_face','قريب — وجه وكتفان','close arm-length front-camera framing focused on head and shoulders with realistic wide-angle facial perspective and no telephoto compression'],
['chest_up','من الصدر للأعلى','front-camera chest-up framing at realistic arm distance with broad smartphone depth of field and natural shoulder perspective'],
['waist_up','حتى الخصر إن أمكن','front-camera framing extending toward the waist only as far as natural arm reach allows; do not move the camera unrealistically far away'],
['seated_high_three_quarter','جالس — مرتفعة ثلاثة أرباع','slightly elevated three-quarter front-camera angle while seated, revealing some torso, seating contact, and nearby environment without overhead geometry'],
['driver_eye_level','داخل السيارة — مستوى العين','driver-held front-camera selfie at eye level inside a stationary vehicle with correct left/right cabin geometry and steering-wheel perspective'],
['driver_slight_high','داخل السيارة — أعلى قليلًا','driver-held front-camera selfie slightly above eye level with gentle downward pitch and physically plausible reach inside the cabin'],
['driver_low','داخل السيارة — منخفضة قليلًا','driver-held front-camera selfie slightly below eye level with mild upward pitch, preserving dashboard and steering-wheel geometry'],
['doorway_three_quarter','بجانب السيارة — ثلاثة أرباع','subject-held front-camera three-quarter angle beside a vehicle, keeping the open or closed door geometry and arm reach physically coherent']
]);

export const LIGHTING_PROFILES = grouped([
['نهاري','day_direct_sun','شمس نهارية مباشرة','direct daytime sunlight from the actual sun direction, hard-to-moderate cast shadows, realistic sky fill, physically consistent highlights, and no exposure setting creating new light'],
['نهاري','day_open_shade','ظل مفتوح نهاري','open shade lit primarily by skylight and reflected environmental light, with soft directional modeling, lower contrast than direct sun, and no invisible fill light'],
['نهاري','day_overcast','سماء غائمة','overcast daylight from a broad sky source, very soft shadows, restrained specular contrast, and physically plausible ambient directionality'],
['نهاري','day_window','ضوء نافذة نهاري','daylight entering through a real window or opening, stronger near the opening and naturally falling off into the room, with plausible wall and floor bounce'],
['نهاري','golden_hour','الساعة الذهبية','low-angle warm sunlight near golden hour with long coherent shadows, warm direct light, cooler sky fill, and realistic atmospheric depth'],
['نهاري','blue_sky_noon','ظهر مشمس قوي','strong high-elevation midday sun with short hard shadows, bright sky fill, realistic heat contrast, and restrained smartphone highlight clipping'],
['نهاري','car_daylight','داخل سيارة نهارًا','daylight entering a stationary car through real glazing, directional window light, dashboard and seat bounce, strong exterior/interior dynamic-range difference, and no artificial cabin key light'],
['تسوق','supermarket_fluorescent','سوبرماركت – فلورسنت','broad ceiling fluorescent lighting typical of Saudi supermarkets, with mild color cast, shelf reflections, and even illumination'],
['تسوق','retail_ceiling_led','متجر – LED سقفي','uniform ceiling LED lighting typical of retail stores, with mild falloff and shelf reflections'],
['تسوق','mixed_retail','متجر – مختلط','mixed retail lighting: ceiling fluorescent plus cooler refrigerated cabinet glow plus warm accent near the entrance'],
['ليلي خارجي','night_led_street','إنارة شارع LED','night scene illuminated only by physically plausible LED street fixtures, localized pools of light, realistic falloff with distance, coherent cast shadows, and dark zones between fixtures'],
['ليلي خارجي','night_parking_led','إنارة موقف سيارات LED','outdoor parking at night lit by practical pole or canopy LEDs with localized pools, inverse-distance falloff, asphalt reflections, and realistic shadow noise'],
['ليلي خارجي','night_storefront','ضوء واجهات محلات','night scene lit by real storefront interiors, signs, and nearby street fixtures, with colored spill only where geometry permits and naturally darker distant areas'],
['ليلي خارجي','night_gas_station','إضاءة محطة وقود','night scene under a real fuel-station canopy with bright overhead practical fixtures, sharp local falloff beyond the canopy, vehicle reflections, and darker surroundings'],
['ليلي خارجي','night_corniche','كورنيش ليلي','night waterfront illumination from real promenade poles and nearby buildings, localized reflections on paving or water, humidity haze, and physically plausible distance falloff'],
['ليلي خارجي','night_desert_vehicle','صحراء ليلية + إنارة سيارة','night desert scene illuminated only by physically present vehicle lamps or nearby practical sources, steep falloff into darkness, limited background visibility, and no artificial moonlike fill unless specified'],
['ليلي داخلي','night_majlis_warm','مجلس — سبوتات دافئة','warm practical ceiling spotlights and fixtures inside the majlis, downward causal light, soft wall bounce, believable facial shadows, and gradual falloff into deeper room areas'],
['ليلي داخلي','night_cafe_mixed','مقهى — إضاءة مختلطة','mixed cafe practical lighting from visible or plausible ceiling LEDs and warm lamps, subtle color-temperature variation, coherent shadows, and no cinematic invisible key light'],
['ليلي داخلي','night_office_led','مكتب — LED أبيض','ordinary office ceiling LED illumination with broad downward light, realistic screen contribution only at close range, restrained shadow contrast, and no studio fill'],
['ليلي داخلي','night_home_warm','منزل — إضاءة دافئة','warm residential practical lighting from ceiling and lamp fixtures, realistic wall bounce, local light falloff, and naturally darker corners'],
['ليلي داخلي','night_phone_screen','شاشة الهاتف كمصدر قريب ضعيف','very weak near-field light from the phone screen only, strongest on the closest facial planes, rapid falloff after the upper chest, deep lower-torso shadow, and no exposure/HDR creating physical illumination'],
['ليلي داخلي','night_car_practicals','داخل سيارة ليلًا — إنارة محيطية واقعية','stationary car interior at night lit by real exterior street or parking fixtures plus restrained dashboard/screen emission, correct glazing reflections, and steep falloff into unlit cabin areas'],
['ليلي داخلي','night_car_screen_only','داخل سيارة — شاشة فقط تقريبًا','very low-light stationary car interior dominated by dashboard or phone-screen emission at close range, rapid falloff across torso and cabin, deep shadows, sensor noise, and no invented fill']
]);

export const HAIR_STYLES = grouped([
['ممشط للخلف','hair-back-natural','ممشط للخلف طبيعي','hair combed back without product, natural strand separation, no gel shine, length and density unchanged'],
['ممشط للخلف','hair-back-lifted','ممشط للخلف مع رفع خفيف','hair combed back with a slight natural lift at the crown, no product shine, density unchanged'],
['ممشط للخلف','hair-slicked-back','Slicked back (مبلل)','hair slicked back with light moisture or product, visible clumping, slight shine, density and hairline unchanged'],
['ممشط للخلف','hair-back-separated','ممشط للخلف مع انفصال طبيعي','hair combed back but with visible natural separation into soft clumps, no uniform gel, density unchanged'],
['ممشط للخلف','hair-back-loose-ends','ممشط للخلف مع أطراف مرتخية','hair combed back with a few loose strands falling near the ears or temples, density unchanged'],
['ممشط للأمام','hair-forward-natural','ممشط للأمام طبيعي','hair brushed forward naturally over the forehead, visible strand separation, density unchanged'],
['ممشط للأمام','hair-forward-quiff','ممشط للأمام مع رفع أمامي','hair brushed forward with a light natural quiff at the front, no product shine, density unchanged'],
['ممشط للأمام','hair-forward-peak','ممشط للأمام بقمة مرتفعة','hair brushed forward with a higher front peak, visible strand texture, density unchanged'],
['ممشط للأمام','hair-forward-side-loose','ممشط للأمام مع خصلات جانبية مرتخية','hair brushed forward with a few strands falling naturally near the temples, density unchanged'],
['ممشط للأمام','hair-forward-partial-forehead','ممشط للأمام نصف منسدل','hair brushed forward with partial forehead coverage, natural strand separation, density unchanged'],
['جانبي','hair-side-part-left','فرق جانبي يسار','hair parted on the left side with a clean visible line, natural fall on both sides, density and hairline unchanged'],
['جانبي','hair-side-part-right','فرق جانبي يمين','hair parted on the right side with a clean visible line, natural fall, density unchanged'],
['جانبي','hair-deep-side-part','فرق جانبي عميق','hair parted deeply on one side, visible scalp at the part line, natural fall, density unchanged'],
['جانبي','hair-side-part-lift','فرق جانبي مع رفع خفيف','hair parted on one side with a natural lift above the forehead, visible strand texture, density unchanged'],
['جانبي','hair-side-part-separated','فرق جانبي + انفصال طبيعي','hair parted on one side with natural clumping and visible strand separation, no product, density unchanged'],
['وسط','hair-center-part-classic','فرق من الوسط كلاسيكي','hair parted down the center with a clean visible line, natural symmetric fall, density unchanged'],
['وسط','hair-center-part-natural','فرق من الوسط مع انفصال طبيعي','hair parted near the center with visible natural strand separation, no product, density unchanged'],
['وسط','hair-center-off','فرق من الوسط غير مضبوط','hair parted slightly off-center naturally, no sharp line, density unchanged'],
['وسط','hair-center-loose','فرق من الوسط مع خصلات مرتخية','hair parted near the center with a few loose strands falling near the face, density unchanged'],
['غير مرتب','hair-messy-natural','messy طبيعي','hair left in a natural messy state with no combing, visible strand crossing and soft volume, density unchanged'],
['غير مرتب','hair-messy-lift','messy مع رفع خفيف','messy hair with a natural lift at the crown, no product, visible separation, density unchanged'],
['غير مرتب','hair-tousled','tousled طبيعي','hair styled in a soft tousled look as if after a long day, natural strand clumping, density unchanged'],
['غير مرتب','hair-wind-light','غير مرتب بعد هواء خفيف','hair slightly displaced by a light breeze or movement, asymmetric but natural, density unchanged'],
['مبلل','hair-damp-post-wudu','مبلل بعد الوضوء','hair slightly damp with visible clumping from moisture, slight darkening at the roots, density unchanged'],
['مبلل','hair-damp-clumped','مبلل مع clumping واضح','hair wet with clear clumping, strand groups visible, natural moisture sheen, density unchanged'],
['مبلل','hair-damp-slicked','مبلل + ممشط للخلف','hair damp and slicked back, visible clumping, slight sheen, density unchanged'],
['مربوط','hair-tied-back','مربوط للخلف بكامل الشعر','hair tied back fully, visible strand separation at the tie point, density unchanged; only length must be enough to tie'],
['مربوط','hair-half-tied','نصف مربوط','hair half-tied with the remaining length falling naturally, density unchanged'],
['مربوط','hair-under-cap','مغطى بطاقية صغيرة','hair fully covered by a small traditional cap, no visible strands outside the cap'],
['مربوط','hair-loose-natural','مرتخي طبيعي بدون تثبيت','hair worn completely loose with no styling product and no fixing, natural fall, density unchanged']
]);

function clean(value) { return typeof value === 'string' ? value.trim() : ''; }
export function normalizeSceneContext(scene = {}) {
  const entries = [
    ['location','Location',clean(scene.location)],['clothing','Clothing',clean(scene.clothing)],['pose','Selfie pose',clean(scene.pose)],['angle','Selfie camera angle',clean(scene.angle)],['lighting','Physical lighting',clean(scene.lighting)],['lighting_notes','Additional lighting notes',clean(scene.lighting_notes)]
  ].filter(([, , value]) => value);
  return Object.fromEntries(entries.map(([key,label,value]) => [key,{label,value}]));
}
export function renderSceneContext(sceneContext = {}) {
  const entries = Object.values(sceneContext);
  if (!entries.length) return '';
  return ['Structured scene controls explicitly selected by the user:',...entries.map((entry)=>`- ${entry.label}: ${entry.value}`),'Treat these controls as explicit scene requirements. Do not override them with aesthetic preferences.'].join('\n');
}
export function sceneConstraintItems(sceneContext = {}) {
  return Object.entries(sceneContext).map(([key,entry],index)=>({id:`scene_constraint_${index+1}`,source_kind:'scene_control',source_key:key,source_text:entry.value,mapping:'semantic',target_section:'relevant_context',target_text:entry.value}));
}